### ISSUE TITLE
Add sample rate command line option to iio_rwdev.

### ISSUE THREAD

**Issue by dlech** [analogdevicesinc/libiio#1055]
`iio_rwdev` is a convenient way to set up trigger and make sure it is working. Currently, however, it is hard coded to use only a default sample rate.

https://github.com/analogdevicesinc/libiio/blob/2322e5a6c90ef669112433c86d9cb2f94f1f9997/utils/iio_rwdev.c#L355-L364

It would be nice to add a sample rate command line option to optionally override the default rate.

**Comment by pcercuei** [comment]
PR #1126 should address this issue.
