### ISSUE TITLE
quiet mode in iio_attr

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/libiio#106]
Currently when asking the setting of one device, things are pretty noisy.

analog@imhotep:~$ iio_attr -u usb:3.80.5  -D loopback
dev 'ad9361-phy', debug attr 'loopback', value :'0'

If you just want the value, you need to get the last field, and strip off the single quotes.

@mhennerich asked for a flag (quiet) that would just do:

analog@imhotep:~$ iio_attr -u usb:3.80.5 -q  -D loopback
0

I think this was to help with a project he @adisuciu were working on.

I wanted to check to see if that was OK with @pcercuei and @larsclausen.

I assume that if you are doing a write:

analog@imhotep:~$ iio_attr -u usb:3.80.5 -q  -D loopback 1
1

the return value is the value after the write.

Thoughts/comments?

**Comment by pcercuei** [comment]
Fine with me.

**Comment by mhennerich** [comment]
submitted a pull request #111

**Comment by rgetz** [comment]
closing
