### ISSUE TITLE
cannot recover when iio_block_dequeue() timeouts

### ISSUE THREAD

**Issue by catkira** [analogdevicesinc/libiio#1109]
I think we briefly talked about this already.

When a call of `iio_block_dequeue()` with nonblock set to false timeouts, the return error is `ETIMEDOUT`. This is fine. What I would expect is that the next call to `iio_block_dequeue()` then tries again for the timeout period that has been set with `iio_context_set_timeout()`. However what happens is that all calls to `iio_block_dequeue()` now immediately return with error code `EPERM` even when new blocks are available to dequeue. 

Can this be changed so that a read timeout is recoverable without having to tear down the whole connection and start everything from new? The current behavior prevents my data link application from doing fast reconnects in case of a connection loss.

**Comment by catkira** [comment]
@pcercuei <3

**Comment by pcercuei** [comment]
@catkira Try my `pcercuei/survive-timeout` branch. Completely experimental, completely untested, of course.

(Note that this branch will generate a non-working IIOD so don't use it on the board.)

**Comment by catkira** [comment]
I will try it tomorrow.

What happens with the data inside a partly filled block when a timeout happens? Is the data discarded or kept inside the partly filled block and returned with the next dequeue command when the block is full?

**Comment by catkira** [comment]
@pcercuei it doesn't work yet, after the first timeout all following dequeue commands return immediately with `ETIMEDOUT`.

**Comment by pcercuei** [comment]
The code I added *should* support network disconnections when they happen between commands, if it is in the process of transferring the data, recovery is a whole lot more difficult...

**Comment by catkira** [comment]
In my case there is no disconnection of the network between the ad9361 and client iio-device, it's just a disconnection of the wireless connection from the ad936x to the other ad936x. In that case the axi_dmac buffer does not get filled anymore from my custom hdl code.

**Comment by catkira** [comment]
For both is fine, if the data of the partially filled block gets discarded or not, because my data stream is tagged so I can detect what is old and new data.

**Comment by catkira** [comment]
The following behaviour would be ok for me in case of dequeue timeout:
a) the partly filled or empty block gets discarded, and the next dequeue command will wait again for the specified timeout 
b) if a block is partly filled, the data inside that block is preserved when a timeout happens and new data is appended to it when the next dequeue command is issued

**Comment by catkira** [comment]
In my case a timeout is always caused because the axi_dmac core does not deliver enough data to fill the block, _not_ because the network connection between iiod running on the ad936x and iio-client running on PC is interrupted.

**Comment by catkira** [comment]
In case of a timeout and a partially filled block the dequeue command can just return with `ETIMEDOUT `, but in that case the user can check the used_bytes flag of the returned block if partial data is available. That would also be harmonious if you add support for the abort feature of the axi_dmac core with dmabuf later.

**Comment by catkira** [comment]
no DMABUF for sure, I think mmap. How can I find out if its mmap or fileio?

**Comment by pcercuei** [comment]
Just add a printf() to `local_dequeue_mmap_block` in local-mmap.c, you'll see if it's called ;)

**Comment by catkira** [comment]
but you said I should not use iiod of this branch right?

**Comment by catkira** [comment]
its a bit difficult because my device stuff is build by buildroot. But I looked at the buildroot log files and all the local-mmap stuff is enabled, so I guess it is used because it has priority over fileio right?

**Comment by catkira** [comment]
this is a grep in my device build dir, WITH_LOCAL_MMAP_API=ON so I think it should use mmap.
<img width="1449" alt="image" src="https://github.com/analogdevicesinc/libiio/assets/13425558/6eeb65ff-baf2-42fb-be50-a07a83a826c1">

**Comment by pcercuei** [comment]
Try with this commit (in my `pcercuei/survive-timeout` branch): https://github.com/analogdevicesinc/libiio/commit/ba3dad4835e193a2ff14c2afebb4cb3caf42795f

**Comment by catkira** [comment]
yes, it does not work. When I try this version on device and client, the call to `iio_create_context()` just hangs.

**Comment by pcercuei** [comment]
Ok, try the `pcercuei/fix-mmap` branch on your target. I did not test timeouts (I don't really have the setup to test it) but it should allow you to re-try dequeueing the blocks.

**Comment by catkira** [comment]
the branch is not there

**Comment by catkira** [comment]
ok now it's there

**Comment by catkira** [comment]
which rev should I use on client?

**Comment by pcercuei** [comment]
I think the main branch is fine, but you need commit 1efcd1b7 (you can just cherry-pick it there).

**Comment by catkira** [comment]
It's not working. iio_info gives this error
```bash
benja@benjaopti7000:~/$ iio_info -u ip:192.168.137.2
ERROR: Unable to create IIO context ip:192.168.137.2: Connection reset by peer (104)
```

**Comment by pcercuei** [comment]
We're working on fixing block enqueue/dequeue here, `iio_info` does nothing of that sort ;)
Make sure you have the right versions installed (`pcercuei/fix-mmap` on the target, main + 1efcd1b on host).

**Comment by catkira** [comment]
yes, but since my app could not create an iio_context I tried to run iio_info on client to see if that can create an iio_context.

**Comment by catkira** [comment]
it would be a good feature if iio_info could show git hash of local and client, currently it only show git tag

**Comment by pcercuei** [comment]
It shows the git tag if the commit it was built from corresponds to a tag, otherwise it shows the git hash :)

**Comment by catkira** [comment]
I am trying this rev now on local
<img width="642" alt="image" src="https://github.com/analogdevicesinc/libiio/assets/13425558/a5d8dbac-248f-4634-9874-1213d03b5f7a">
but `iio_info` on local still only shows the tags
<img width="725" alt="image" src="https://github.com/analogdevicesinc/libiio/assets/13425558/c992fdc0-deae-4d91-acd0-a70d4c72d2c9">

**Comment by pcercuei** [comment]
I think your problem is that Buildroot strips the .git subfolders when extracting the sources (or it downloads the release tarball from github, which does not have the .git subfolder). Libiio's CMake then cannot compute the git hash.

**Comment by catkira** [comment]
the 61fdbe rev also could not connect, I tried a rev that's a bit older on local and it works again
d905a5bc1f6b7061073c95641482e3af152f98f9

**Comment by catkira** [comment]
I think there are some changes unrelated to the current dequeue effort that broke some things for me

**Comment by catkira** [comment]
72e8276b62371cbc1c802cc265c873d7695fd6b4 is broken, so somewhere between 72e8276b62371cbc1c802cc265c873d7695fd6b4 and aa2aa8ee06a380d9830adb4c8c5e8f6a3ccfc68e must be a problem.

**Comment by pcercuei** [comment]
The problem is `72e8276b`.

**Comment by pcercuei** [comment]
@catkira I force-pushed the `pcercuei/fix-mmap` branch, and rebased the changes on top of the last known good commit. And I'll have a look at that other problem later.

**Comment by catkira** [comment]
after the first timeout all following calls to dequeue immediately return with `ETIMEDOUT`, maybe you forgot to reset the timeout counter somewhere?

**Comment by catkira** [comment]
or maybe the timeout flag of the file descriptor needs to be cleared?

**Comment by pcercuei** [comment]
> after the first timeout all following calls to dequeue immediately return with `ETIMEDOUT`, maybe you forgot to reset the timeout counter somewhere?

Can you try to reproduce it on the target directly first? Do you also get `ETIMEDOUT` when trying to dequeue a new block there?

> after a timeout, is the block dequeued or not. Should the next dequeue command be issued with the same block or the next block?

After a timeout you can consider that the dequeue operation failed, so you should re-try with the same block.

**Comment by catkira** [comment]
> > after the first timeout all following calls to dequeue immediately return with `ETIMEDOUT`, maybe you forgot to reset the timeout counter somewhere?
> 
> Can you try to reproduce it on the target directly first? Do you also get `ETIMEDOUT` when trying to dequeue a new block there?

that is not easily possible, because my client app has a GUI and cannot run on the ZYNQ device.

> 
> > after a timeout, is the block dequeued or not. Should the next dequeue command be issued with the same block or the next block?
> 
> After a timeout you can consider that the dequeue operation failed, so you should re-try with the same block.

ok that is what I expected.

**Comment by catkira** [comment]
Do you think the problem is that `buffer_check_ready()` does not wait after the first timeout occured?

**Comment by catkira** [comment]
can you make a revision with some debug printfs that I can observe on local terminal?

**Comment by pcercuei** [comment]
The behaviour you originally reported is that it would report `-EPERM` the second time you call `iio_block_dequeue`. Why do you get `-ETIMEDOUT` now? Can you try with the `pcercuei/fix-mmap` branch on the target, and the main branch on the PC?

**Comment by catkira** [comment]
this is what I did, main + this extra commit on pc and fix-mmap on target

**Comment by catkira** [comment]
When I try with `pcercuei/fix-mmap` on PC as well I get `Operation not permitted (1)` after the first timeout.

**Comment by pcercuei** [comment]
I think there are actually two issues, one on the target side which should have been fixed with the `pcercuei/fix-mmap` branch, and another one on the PC side. With the new protocol the block enqueue/dequeue is actually one single command; `iiod_client_enqueue_block` will send the command, and `iiod_client_dequeue_block` will read the answer.

This is annoying because it means that if dequeueing times out, `iiod_client_dequeue_block` won't actually re-send the command, and that's why you get the timeout error. And you can't re-send the command anyway, since technically the block will have been enqueued on the IIOD side already and can't be enqueued a second  time.

I think I can come up with a solution, but not before the end of the year.

**Comment by catkira** [comment]
ok, I will just wait then. Thanks for the effort!

**Comment by catkira** [comment]
maybe it's better to dequeue the block everywhere after a timeout and then do the next dequeue command with the next block?

**Comment by pcercuei** [comment]
Can you try my `pcercuei/fix-mmap` branch again? On both sides.

**Comment by catkira** [comment]
now I don't get any timeout, instead I get a `Operation not permitted (1)` when a timeout should happen.

**Comment by catkira** [comment]
and no timeout return from the dequeue call

**Comment by catkira** [comment]
I think what happens now is that in case of a timeout it is not signalled correctly by the return value of `iio_block_dequeue()` and then the next call to `iio_block_enqueue()` fails with `Operation not permitted (1)` because the timeout block is still enqueued.

**Comment by pcercuei** [comment]
Ok, now `iio_block_dequeue()` should return the timeout error.

**Comment by catkira** [comment]
I only have to update client right?

**Comment by catkira** [comment]
it seems to be working now!

**Comment by pcercuei** [comment]
That's great!
I will have to rework the code a bit (but not this year :p) because since we send the `IIOD_OP_RETRY_DEQUEUE_BLOCK` command the moment the `iio_block_dequeue` times out, we actually start the timeout timer before the application actually calls `iio_block_dequeue` again.

**Comment by pcercuei** [comment]
@catkira I reworked the code (still in the `pcercuei/fix-mmap` branch), now the `IIOD_OP_RETRY_DEQUEUE_BLOCK` is sent on the second call to `iio_block_dequeue`. Can you confirm that it still works?

**Comment by catkira** [comment]
I rebased the fix-mmap branch on master before the iio_event stuff was added because my applications need to open multiple contexts locally. 
https://github.com/catkira/libiio/commits/fix-mmap-rebased/
Do you think you can make it possible to open multiple contexts locally with the new iio_event stuff? Otherwise I would have to cherry-pick everything I should test and it becomes quite messy.

**Comment by catkira** [comment]
I just have to cherry-pick the 5 commits you did 2 days ago onto my rebase branch to test this right?

**Comment by catkira** [comment]
or is it enough if I test the new commits on remote? Then I could use your branch directly.

**Comment by pcercuei** [comment]
> I just have to cherry-pick the 5 commits you did 2 days ago onto my rebase branch to test this right?

Yes. Or test it on top of PR #1118.

**Comment by catkira** [comment]
can you rebase [onto fix-mmap](https://github.com/analogdevicesinc/libiio/tree/pcercuei/fix-mmap) onto [pcercuei/local-buffer-fd](https://github.com/analogdevicesinc/libiio/tree/pcercuei/local-buffer-fd) ?

**Comment by pcercuei** [comment]
done.

**Comment by catkira** [comment]
Thanks, I will test it this evening (my datalink hardware is at home).

**Comment by catkira** [comment]
something is not working, I cannot connect from remote to local iio
```bash
benja@DESKTOP:~$ iio_info -u ip:192.168.137.2
ERROR: Unable to create IIO context ip:192.168.137.2: Connection reset by peer (104)
```

**Comment by catkira** [comment]
It works when I use [pcercuei/fix-mmap](https://github.com/analogdevicesinc/libiio/tree/pcercuei/fix-mmap) on remote and [catkira/fix-mmap-rebased](https://github.com/catkira/libiio/commits/fix-mmap-rebased/) on local

**Comment by pcercuei** [comment]
I rebased on top of master, and using pcercuei/fix-mmap on both sides, it works fine here.

**Comment by catkira** [comment]
It's working when I use top of main on both sides (except that it cannot recover from timeouts). So I guess something with the fix-mmap or rebase of fix-mmap is wrong. fix-mmap was working before the rebase, so it's probably the rebase.

**Comment by catkira** [comment]
> I rebased on top of master

you mean top of main? (all main branches should be called master ^^)

**Comment by pcercuei** [comment]
On top of "main" yes.

What exactly does not work? You get the "connection reset by peer" message? Does IIOD say anything?

**Comment by catkira** [comment]
oh, everything is working now. It was a n00b mistake on my side, I did not do `git reset --hard` after the fix-mmap rebase ^^
sorry!

**Comment by pcercuei** [comment]
Can you confirm:
- that block dequeue after timeouts work correctly;
- that the problem with the buffer FD being kept open at all times is gone?

**Comment by catkira** [comment]
yes, both things are working.

**Comment by lorenzobonomo** [comment]
Hi, i m having the same problem. I m trying to use my zcu102 with ADRV9002. I build the yocto project following the edf framework. The problem is that when i try t launch the command sudo iio_readdev -u local: -T 1 -b 64 -s 32 axi-adrv9002-rx-lpc voltage0_i voltage0_q | od -An -td4 it gives me ERROR: iio:device2: Unable to dequeue block: Connection timed out (110)%0D%0AERROR: iio:device2: Unable to get next block: Connection timed out (110). The strange things is that while i have problm with the RX, the TX works perfectly. Can anyone help me pls?

**Comment by dNechita** [comment]
Hi,
The `iio_readdev` ships only with libiio v0. This discussion thread is about libiio v1. The concept of block exists in both versions.
Regarding your issue: does it work if you increase the timeout?
