### ISSUE TITLE
CODE_OF_CONDUCT.md outdated

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/libiio#1113]
https://github.com/analogdevicesinc/libiio/blob/main/CODE_OF_CONDUCT.md

includes my old (non-functional) email address.

> robin (dot) getz (at) analog (dot) com

someone should update that with new data.

**Comment by pcercuei** [comment]
@rgetz can you send a PR to update it?

**Comment by rgetz** [comment]
No - I don't know who to [voluntold](https://www.collinsdictionary.com/submission/7211/voluntold).

@mhennerich or @stephenkilbaneadi needs to nominate someone. They should send the PR (IMHO). 

I just know it's not me. :)

**Comment by stephenkilbaneadi** [comment]
Thanks, Robin. PR submitted.

**Comment by mhennerich** [comment]
Thanks, I think we can close this now.
