### ISSUE TITLE
Systemd warns about unset variables

### ISSUE THREAD

**Issue by dennis-ju** [analogdevicesinc/libiio#1142]
During startup of iiod, we get the following warning:
`iiod.service: Referenced but unset environment variable evaluates to an empty string: IIOD_EXTRA_OPTS`

This is because since v254 of systemd, unset environmental variables will result in a warning (see [commit](https://github.com/systemd/systemd-stable/commit/f331434d13488425ccd8485327085d15f8f92aea)).

I could make a PR where I add this to the service file:
`Environment=IIOD_EXTRA_OPTS=''`

Would this be a good solution?

**Comment by dennis-ju** [comment]
Yes, I believe that adding the line `Environment=IIOD_EXTRA_OPTS=''` would set it to an empty string while still being overridden if it is set in `/etc/default/iiod`. 

In the systemd manual (see [link](https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html)) under `EnvironmentFile=` it says "Settings from these files override settings made with Environment=."

**Comment by dennis-ju** [comment]
Is there a possibility that we could add this to the legacy branch?

**Comment by mhennerich** [comment]
> Is there a possibility that we could add this to the legacy branch?

Yes

**Comment by mhennerich** [comment]
Lets re-open

**Comment by dennis-ju** [comment]
Unfortunately the issue is not solved yet. A rogue dollar sign causes the assignment of IIOD_EXTRA_OPTS to be invalid. I'll add a new fix soon.
