### ISSUE TITLE
what steps exactly to run ad9361-iiostream

### ISSUE THREAD

**Issue by Argonghost** [analogdevicesinc/libiio#1149]
hi,

what steps exactly do i need to run the ad9361-iiostream.c example???
I cannot seem to compile normally via ``gcc`` .  I have the impression that running ad9361 streaming example requires use of CMakeLists and ``make`` etc.  My goal is to run the ad9361-iiostream example on my linux machine connected to pluto via usb.  What steps should i follow to do that? 

thanks

**Comment by tfcollins** [comment]
CMake is not required. Just link against libiio 

'''bash
wget https://github.com/analogdevicesinc/libiio/blob/libiio-v0/examples/ad9361-iiostream.c
gcc -o ad9361-iiostream ad9361-iiostream.c -liio 
'''

**Comment by Argonghost** [comment]
> CMake is not required. Just link against libiio 
> 
> ```bash
> wget https://github.com/analogdevicesinc/libiio/blob/libiio-v0/examples/ad9361-iiostream.c
> gcc -o ad9361-iiostream ad9361-iiostream.c -liio 
> ```

I get the error ´´segmentation fault core dumped ´´

Even despite entering my usb id

**Comment by tfcollins** [comment]
Can you provide the command and full output? Have you tried to get a backtrace?

**Comment by Argonghost** [comment]
> Can you provide the command and full output? Have you tried to get a backtrace?

What is backtrace??
Regarding the full command its as you provided, the full output is: 

Segmentation fault (core dumped)

**Comment by tfcollins** [comment]
> What is backtrace??

This is a standard debugger output up to a failure. If you are not familiar with C debugging in Linux I would google around for gdb tutorials on basic debugging. 

 

> Regarding the full command its as you provided, the full output is:
> 
> Segmentation fault (core dumped)

This does not include the commands you used

**Comment by Argonghost** [comment]
hi @tfcollins 

yes i forgot backtrace means ```gdb``` and ```run```.  on AD wiki i was finally shown how to properly define cmake to finally get it up and running .  

Thanks,
