### ISSUE TITLE
C# binding not implementing iio_context_get_attr

### ISSUE THREAD

**Issue by Manawyrm** [analogdevicesinc/libiio#115]
Hi,

the c# binding doesn't seem to implement a way to access the Context attributes, normally accessed via iio_context_get_attr.

**Comment by rgetz** [comment]
The C# bindings were added before context attributes existed, so it's possible it wasn't updated. 

Thanks for pointing it out.

**Comment by Manawyrm** [comment]
Off-Topic: 
I need to use the libad9361/ad9361_set_bb_rate function in C#. 
There isn't a binding for that atm; Would you recommend I create such a binding, or should I rather reimplement the functionality in C# nativly?

**Comment by pcercuei** [comment]
Should be very easy to add.

**Comment by lclausen-adi** [comment]
@Manawyrm looks like you have the best C# skills around here and an environment to test things, do you think you can send a patch?

**Comment by rgetz** [comment]
iio_context_get_attr is still missing from bindings/csharp/Context.cs

**Comment by rgetz** [comment]
either Dan or Adrian - can you have a look at this?

**Comment by dNechita** [comment]
Yes

**Comment by rgetz** [comment]
Thanks

**Comment by rgetz** [comment]
I think this is just a specific version of #364, so we will close this, and make sure it's addressed as part of that one. @Manawyrm feel free to comment there on what you think you need.

Thanks
-Robin
