### ISSUE TITLE
"Unable to parse XML File" Error after updating radio-side libiio to latest revision

### ISSUE THREAD

**Issue by catkira** [analogdevicesinc/libiio#1152]
This error message is shown on my client console when I execute create iio context
![image](https://github.com/analogdevicesinc/libiio/assets/13425558/a30a258e-402e-4d3b-b717-99c26ed6629a)

revision 7ae483696affb64ab6e1766f55e47f00456593d0 is working fine

**Comment by pcercuei** [comment]
Weird.
I did update the XML backend here: https://github.com/analogdevicesinc/libiio/commit/5f4f76085c603138ea639f4b9b91865956e54419
So maybe a bug slipped through.

**Comment by catkira** [comment]
This PR https://github.com/analogdevicesinc/libiio/pull/1173 fixes it.
