### ISSUE TITLE
Vitis 2023.2 can't find iio.h file path??

### ISSUE THREAD

**Issue by FarukSozuer** [analogdevicesinc/libiio#1158]
Hello everyone,
I want to add libiio to my project using Petalinux 2023.2. I didn't have problems before, but I can't find the path to iio.h in vitis, even though I can use the bbappend content as is. If I were to list what I did in order;
1. I created it in libio file under petalinux meta-user->recipes-support.
2. I copied the bb file and patch file in the link https://github.com/analogdevicesinc/meta-adi/tree/main/meta-adi-xilinx/recipes-support/libiio as they are.
3. After the petalinux-puild and petalinux-package, I created a new project in vitis and got an error that it could not find the iio.h file.

I didn't get any errors during petalinux-build.

**Comment by tfcollins** [comment]
Please open a thread here as this is not specific to libiio itself: https://ez.analog.com/ in the Linux-drivers subforum.

-Travis
