### ISSUE TITLE
RX data loss on on pluto and other SDRs

### ISSUE THREAD

**Issue by vvsvvsvvs** [analogdevicesinc/libiio#1167]
When RX is on, the number of buffers (default 4) NB_BLOCKS in iiod is too small, so there are data duplicates when operating on high rates (>= 3Msmpl/sec). So, increasing the value (16+) solves the problem.
Also reported on
[](https://ez.analog.com/adieducation/university-program/f/q-a/557389/missing-every-other-transmission-between-two-plutosdrs-using-gnuradio/455544)
Also, the 16+ buffers reduces the temperature of AD (hm...ok).
Tested on Pluto+ SDR.

**Comment by tfcollins** [comment]
Not really sure what the question(s) are here. Overflows are really dependent on a few settings and not just number of buffers, as well as the behavior of your program.

Pluto+ is not an ADI product so we would point you to the maintainer.
