### ISSUE TITLE
[Windows] Error when running iio_info

### ISSUE THREAD

**Issue by SrikanthPagadarai** [analogdevicesinc/libiio#1174]
I grabbed the latest Azure builds for Windows and ran iio_info -s. It opens an error window with the message "The procedure entry point sp_blocking_read could not be located in the dynamic link library C:\WINDOWS\system32\libiio1.dll."

**Comment by tfcollins** [comment]
A few things:
- Based on the iss file libzstd is not included but its built against it in CI
- Serial support seems broken on Windows
- Python bindings are also broken on Windows

**Comment by cristina-suteu** [comment]
@tfcollins regarding the serial support , a fix was added here https://github.com/analogdevicesinc/libiio/pull/1163 , is serial support still broken after this ? 
as for the other things, i'm working on fixing them

**Comment by rgetz** [comment]
I think this is fixed, and can be closed?
