### ISSUE TITLE
Clarification that iio_context was successfully destroyed

### ISSUE THREAD

**Issue by SgoSkz** [analogdevicesinc/libiio#1186]
Is there a way to confirm that iio_context ptr has been destroyed properly after calling iio_context_destroy(ctx*)?

**Comment by tfcollins** [comment]
A dependent library may set an error code in the system but libiio itself has no error state on destroy, or maybe it's best to say it's undefined behavior. So the behavior is similar to free in C which has no check.

If you run destroy set the pointer to NULL.
