### ISSUE TITLE
Is the Libiio support ADRV9025?

### ISSUE THREAD

**Issue by deltaRing** [analogdevicesinc/libiio#1218]
Hello community,
 I am using the zcu102 + adrv9026 and libiio for capturing and transmitting signal. However, i can emit nothing but noise during using the libiio. The code is modified based on the adrv9009-iostream.c. Now my question is the libiio c code support adrv9026? Any suggestion is appreciated!

**Comment by deltaRing** [comment]
can anyone help me😭😭😭？

**Comment by deltaRing** [comment]
okay, looks like my address of the txbuf is changed in each iteration, i'm try to find out what happening to txbuf

**Comment by ekigwana** [comment]
> okay, looks like my address of the txbuf is changed in each iteration, i'm try to find out what happening to txbuf

Search through the support forums here https://ez.analog.com/rf/wide-band-rf-transceivers/design-support-adrv9026

And be sure to search for similar "issues" for the AD9361 and you will find that several before you have encountered this and usually it comes down to how the hardware is configured and understanding that. The Engineer Zone is the best place for best effort support.

**Comment by deltaRing** [comment]
okay, guys, i've figured out what's the problem of my adrv9025. 

First, adrv9025 utilized the LSB data only, so the above examples utilize MSB would not work correctly.
![image](https://github.com/user-attachments/assets/59ab7c9c-dacb-4866-8dbf-187c82118030)

Then, the adrv9025 TX4 utilize LO2 by default, so i've set both LO1 and LO2 to the same frequency（That's why i can't receive any data due to i've set LO1 only）
![image](https://github.com/user-attachments/assets/df8166b5-f358-46c9-846e-4b416fca308b)

Next, i've noticed the hardwaregain is low, and i increased it to 0.0dB
![image](https://github.com/user-attachments/assets/c8191071-f47b-4d5d-b5f6-8e5345494ef2)

finally, i can receive the signal in my another device (ad9361)
![da51858e598a26bbbba346ef24715b3](https://github.com/user-attachments/assets/a5726a5b-1cb0-45dc-9756-e579c0b3b04f)
![6ff76584d71f0a25a5ad5bd840a96e7](https://github.com/user-attachments/assets/97df6718-2751-4102-bd97-06ce5adb8096)

As for the above address problem, i've tested it, and it can be my mistake. I input wrong address. everything is pretty normal now.

Thank you for your reading and helping!
