### ISSUE TITLE
JavaScript bindings

### ISSUE THREAD

**Issue by drom** [analogdevicesinc/libiio#125]
I want to use `iio` from my nodejs application. Do you have plans for the official JavaScript / NodeJS binding in the near future? Or I should go ahead and implement my own library?

**Comment by lclausen-adi** [comment]
Hi,

We don't have any plans for adding this at the moment. But patches are always welcome :)

**Comment by drom** [comment]
I am working on `libiio` bindings here: https://github.com/drom/node-iio

**Comment by pcercuei** [comment]
Nice :)

**Comment by pcercuei** [comment]
If you want, we can host the code inside the main repository, maybe that will give it more visibility.
I will close this bug report now that we effectively have JavaScript bindings.

**Comment by drom** [comment]
yes, I think it makes sense to move it into the main repository and mention its existence over the official LIBIIO channels. I am not using it at the moment, but other people may find it useful.

**Comment by rgetz** [comment]
@drom : Did you want to make a pull request? Right now (we will just point to your repo - not yet live doc at https://rgetz.github.io/libiio/v0.19/index.html )

**Comment by drom** [comment]
@rgetz I am actually OK with this Node.js IIO binding being a separate repo. I can move it into some `IIO` or `analogdevicesinc` org if there are concerns about maintainability. In the Node.js world, people appreciate small, "a single concern" modules. I also publish in on NPM as `libiio` where most of JS people will find it.

**Comment by rgetz** [comment]
@drom - sounds great. I will also point to NPM as well... Thanks for the tip.
