### ISSUE TITLE
appveyor.yml: MinGW builds for Windows 32 bit and 64 bit: Add README.txt

### ISSUE THREAD

**Issue by mhennerich** [analogdevicesinc/libiio#140]
appveyor.yml: Create MinGW builds for Windows 32 bit and 64 bit. #124 

https://github.com/analogdevicesinc/libiio/pull/124 was merged without README.
Add missing README.txt

**Comment by rgetz** [comment]
sorry - forgot about this.

**Comment by rgetz** [comment]
Readme was added commit 3ac535b0abe0f96ca01332a629d59c678d8bdbc1

Assigning to @AlexandraTrifan; so she can add things to the zip file in the appveyor.yml file.

**Comment by AlexandraTrifan** [comment]
Readme was added in the zip file with commit aa4929366a7fcb580869d988129e3b8edd0766fd.

**Comment by rgetz** [comment]
closing
