### ISSUE TITLE
C# Binding - IIOBuffer.fill() Overflow

### ISSUE THREAD

**Issue by raceybe** [analogdevicesinc/libiio#153]
In IIOBuffer.cs, the fill() method reports an overflow when the iio_buffer_end(buf) and iio_buffer_start(buf) Intptr is cast to int. Changing the cast to long prevents this overflow...does this depend on the bitness of the OS or the bitness the DLL is compiled for?

`int length = (int) iio_buffer_end(buf) - (int) iio_buffer_start(buf);`
becomes
`long length = (long) iio_buffer_end(buf) - (long) iio_buffer_start(buf);`

**Comment by pcercuei** [comment]
I guess it should be "long", yes. Could you send a patch?

**Comment by rgetz** [comment]
@AlexandraTrifan : can you have a look at this?

**Comment by rgetz** [comment]
Pull request merged - so closing this issue.
