### ISSUE TITLE
master failing in appveyor

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/libiio#163]
according to:

https://ci.appveyor.com/project/analogdevicesinc/libiio/history

we are failing due to:

-- Looking for lzma_auto_decoder in C:/msys64/mingw64/lib/liblzma.dll.a
-- Looking for lzma_auto_decoder in C:/msys64/mingw64/lib/liblzma.dll.a - not found
-- Looking for lzma_easy_encoder in C:/msys64/mingw64/lib/liblzma.dll.a
-- Looking for lzma_easy_encoder in C:/msys64/mingw64/lib/liblzma.dll.a - not found
-- Looking for lzma_lzma_preset in C:/msys64/mingw64/lib/liblzma.dll.a
-- Looking for lzma_lzma_preset in C:/msys64/mingw64/lib/liblzma.dll.a - not found
CMake Error at C:/msys64/mingw32/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibLZMA (missing: LIBLZMA_HAS_AUTO_DECODER
  LIBLZMA_HAS_EASY_ENCODER LIBLZMA_HAS_LZMA_PRESET) (found version "5.2.3")

This use to work (last passing log):
https://ci.appveyor.com/project/analogdevicesinc/libiio/build/2015.1.1085

Looking for lzma_auto_decoder in C:/msys64/mingw32/lib/liblzma.dll.a
-- Looking for lzma_auto_decoder in C:/msys64/mingw32/lib/liblzma.dll.a - found
-- Looking for lzma_easy_encoder in C:/msys64/mingw32/lib/liblzma.dll.a
-- Looking for lzma_easy_encoder in C:/msys64/mingw32/lib/liblzma.dll.a - found
-- Looking for lzma_lzma_preset in C:/msys64/mingw32/lib/liblzma.dll.a
-- Looking for lzma_lzma_preset in C:/msys64/mingw32/lib/liblzma.dll.a - found
-- Found LibLZMA: C:/msys64/mingw32/include (found version "5.2.3") 

and i don't think we changed anything on the libiio side...

-Robin

**Comment by lclausen-adi** [comment]
Fixed with #169.
