### ISSUE TITLE
Enabling high-speed mode fails with -EINVAL (Invalid argument)

### ISSUE THREAD

**Issue by krisklau** [analogdevicesinc/libiio#165]
Hi! 

I am working with the adis16488, and had some trouble getting iio going. When opening the buffer (with custom app or the oscilliscope program), I constantly got "Unable to open buffer: Invalid argument". 

It turned out to be the call to enable high-speed that failed:
https://github.com/analogdevicesinc/libiio/blob/7dddeeccf807766d5acc7b95dd793383c3ec8070/local.c#L956

enable_high_speed:
https://github.com/analogdevicesinc/libiio/blob/7dddeeccf807766d5acc7b95dd793383c3ec8070/local.c#L811

Specifically, `ret = ioctl_nointr(fd, BLOCK_ALLOC_IOCTL, &req);` returns with `-EINVAL`. 

There seems to be logic to continue without using high_speed if the call returns ENOSYS. However, I can't see where the ioctl-kernel calls would return ENOSYS if high-speed is disabled, and even where the high-speed ioctl-calls are handled at all, as I cant find any reference to the _IOWR-definitions in the kernel. (e.g. `#define BLOCK_ALLOC_IOCTL _IOWR('i', 0xa0, struct block_alloc_req)`

Am I correct that this is the receiving kernel function?
https://github.com/torvalds/linux/blob/60cc43fc888428bb2f18f08997432d426a243338/drivers/iio/industrialio-core.c#L1610

My fix was to patch iio to skip trying to enable high-speed, which leads to my questions:

1. Am I supposed to use some custom kernel-patches to use high-speed? I see some references to high-speed in [these slides](http://events17.linuxfoundation.org/sites/events/files/slides/iio_high_speed.pdf) where it says the code is still not upstream, but I'm unsure of the dates of these slides. 
2. What would be the correct approach to disable high-speed without patching iio? 

(Tested on kernel 4.1.44, NXP/Freescale iMX7, ARM Cortex-A7)

Thanks for any inputs, I'm looking forward to working more with libiio!

Best,
Kristian

**Comment by lclausen-adi** [comment]
Hi,

Thanks for the report. I think this is my fault, looks like the issue got introduced with commit e6754cb84a8b9d1ab5b79bb44dca18bcffde3236.

We'll fix it.

**Comment by rtresidd** [comment]
Cheers Lars
   Funny we all hit the same issue within a couple of days of each other.

**Comment by rtresidd** [comment]
Hi Lars
       I can confirm that this fixes the issue I was seeing with using
    buffers on low speed devices.
    Cheers
      Richard Tresidder
    
    Reviewed-by: Richard Tresidder
    <rtresidd@tresar-electronics.com.au>
    
    
    On 2/05/2018 8:19 PM, Lars-Peter
      Clausen wrote:
    
    
      @krisklau
        @rtresidd
        Sorry, for the delay on solving this issue.
      Can you verify that low-speed mode works for you with commit 94ba7e4.
      Thanks.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/analogdevicesinc/libiio","title":"analogdevicesinc/libiio","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/analogdevicesinc/libiio"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lclausen-adi in #165: @krisklau @rtresidd Sorry, for the delay on solving this issue.\r\n\r\nCan you verify that low-speed mode works for you with commit 94ba7e4b866aaaaa75f5cd76837fe598780d8d8a.\r\n\r\nThanks."}],"action":{"name":"View Issue","url":"https://github.com/analogdevicesinc/libiio/issues/165#issuecomment-385958659"}}}
