### ISSUE TITLE
Publishing Python bindings in PyPi

### ISSUE THREAD

**Issue by afonso360** [analogdevicesinc/libiio#191]
Hi,

It looks like the python bindings for `libiio` are not available in PyPI. I'd like to know if there are any plans for this.

Thanks

**Comment by pcercuei** [comment]
You mean pip?

**Comment by afonso360** [comment]
Yes, pip uses PyPI by default to provide packages

**Comment by rgetz** [comment]
I don't think we have any immediate plans - but we do accept patches.

It looks pretty straight forward -
https://packaging.python.org/tutorials/packaging-projects/

**Comment by rgetz** [comment]
@tfcollins any opinions? I know you have been doing a bunch of pip stuff recently.

Thanks
-Robin

**Comment by tfcollins** [comment]
This would be really nice to have and make installing pyadi-iio at least easier. I've used cmake dependent pip modules in the past, but they didn't have external dependencies like libiio does. This might take some research.

**Comment by tfcollins** [comment]
It seems as pip has no standard way of dealing with non-python dependencies, which kinda makes sense. I see a few ways of moving forward

1. Assume the C library itself is installed and simply place the bindings. Checking for libiio across platforms isn't easy.
2. Assume the dependencies exist and just install a built release from Github. Very error-prone and most will not have the deps beforehand.
3. Implement the necessary calls to the local package manager with things like `deb-pkg-tools`  and install everything. This would have to be implemented on each OS variant and would not work on windows.

**Comment by rgetz** [comment]
For your 1, isn't just a try around the _cdll function?

https://github.com/analogdevicesinc/libiio/blob/master/bindings/python/iio.py#L69

if that errors - that would tell you to install the .so/.dll/framework for your arch? There is already platform specific code which finds the dll, framework or so you should be able to use that?

```
if 'Windows' in _system():
        _iiolib = 'libiio.dll'
       _install_err = 'Error finding the dll, install the windows installer'
```

the error would be something like 
```
print(_install_err + 'from 
https://github.com/analogdevicesinc/libiio/releases/latest')
```

Something like that? I think that would be the best idea (lowest effort/high impact?)

Thanks
- Robin

**Comment by tfcollins** [comment]
First stab: https://github.com/analogdevicesinc/libiio/blob/pip-install/bindings/python/setup.py.cmakein

Will take some testing but luckily pip has a testing variant of their main install repos.

**Comment by rgetz** [comment]
This works pretty well for me. 

Did you want to include this as a PR?

**Comment by tfcollins** [comment]
I need to test here first to make sure packaging isn't broken.

**Comment by tfcollins** [comment]
Should we support python2?

**Comment by pcercuei** [comment]
The bindings do support both Python2 and Python3, so I'd be in favor of supporting it - at least until it is really dead.

**Comment by tfcollins** [comment]
Ok I updated the installer to handle both cases and both seem to work once put on pypi as well. Just need to work with Alex to get CI to push to pypi.

**Comment by rgetz** [comment]
👍 sounds great - thanks

**Comment by rgetz** [comment]
I think this is in the the [Cmake](https://github.com/analogdevicesinc/libiio/blob/master/.travis.yml#L159-L167) now, so I will close this, and check on the next release.
