### ISSUE TITLE
LIbiio with intel edison

### ISSUE THREAD

**Issue by sriranjanr** [analogdevicesinc/libiio#21]
Hello,

I want to run the ADC on intel edison at 8khz.Is it possible to achieve this with libiio on edison?

**Comment by rgetz** [comment]
The ADC found in the Edison is the ADS7951. I don't know if there is a Linux IIO kernel driver for that part. You should check with the converter manufacture (http://www.ti.com/product/ads7951), or the PCB manufacturer (Intel). 

If there is a driver that works - libiio should work without issue.

**Comment by sriranjanr** [comment]
Found some drivers here but not for ADS7951.
https://github.com/torvalds/linux/tree/master/drivers/iio/adc
Is it possible to quickly write a driver for it.
