### ISSUE TITLE
how to install iio python package using installer

### ISSUE THREAD

**Issue by shinong** [analogdevicesinc/libiio#243]
Hi,
I installed the package on my mac using the installer. I also want to install the python iio package on this computer. When I run the setup.py.cmakin file in the /binding/python, it has an error message as 'error: package directory '${CMAKE_CURRENT_SOURCE_DIR}' does not exist'. I wonder how I can install the package properly?

Thanks,
Shinong

**Comment by krsch** [comment]
If you change `${CMAKE_CURRENT_SOURCE_DIR}` to `.` and `${VERSION}` to libiio version you can run `python ./setup.py` normally.

**Comment by rgetz** [comment]
I think this is resolved - if you have any other issues - please let us know.
