### ISSUE TITLE
iio_readdev gives corrupted data on native windows (7 and 10)

### ISSUE THREAD

**Issue by meds7** [analogdevicesinc/libiio#257]
Hi, 
I tested iio_readdev data retrieval from a network backend which is able to send data at 125Mbit/s as iio device. It appears that both W7 and W10 native libiio (0.17 tested) results in corrupted data retrieval. 
Tests on the same W10 machine but using WSL works great.

Henk Medenblik

**Comment by commodo** [comment]
could you give us some input on the libiio you used ?
did you build it yourself, or did you use an installer built by us ?

thanks
Alex

**Comment by meds7** [comment]
Dear Alexandru,

For this test I used the installer which can be found at https://ci.appveyor.com/api/projects/analogdevicesinc/libiio/artifacts/libiio-setup.exe?branch=master

I hope that helps to identify it. Let me know if I can help you further to identify the problem.

With kind regards !
Henk

**Comment by rgetz** [comment]
OK - we will try to have a look at this before the next release. @dNechita - do you have time?

**Comment by dNechita** [comment]
> OK - we will try to have a look at this before the next release. @dNechita - do you have time?

Yes, I will look into this before we do the next release.

**Comment by dNechita** [comment]
Hi @meds7 

Sorry for this very late reply!

Do you remember which bash did you use to run the iio_readdev example on Windows7/10?

**Comment by rgetz** [comment]
I think he said “W7 and W10 native libiio“. So no bash - just a native windows prompt. (cmd)

**Comment by meds7** [comment]
Hi @dNechita , @rgetz 

Indeed, the issue is with native Windows as @rgetz  pointed out. Unfortunately my piece of hardware has been shipped to the end customer already for a long time ago so I can’t verify any new changes.

Regards,
Henk

**Comment by dNechita** [comment]
The issue in not in the libiio library but in the iio_readdev program.
I have the fix in the PR. It was an issue of how stdio works on windows.

**Comment by rgetz** [comment]
thanks for fixing.
