### ISSUE TITLE
Add macOS 10.14 (Mojave) to built releases

### ISSUE THREAD

**Issue by tfcollins** [analogdevicesinc/libiio#272]

**Comment by mhennerich** [comment]
Now that travis-ci supports macOS 10.14 add it to the build maxtrix  and possibly drop 10.12

**Comment by rgetz** [comment]
I think this is done now?

https://github.com/analogdevicesinc/libiio/blob/master/.travis.yml#L69

We are building xcode9.2 and xcode10.1

https://docs.travis-ci.com/user/reference/osx/#macos-version

says we are missing xcode11 or  xcode10.1 (macOS 10.14)

@tfcollins - any preference - I don't think it is necessary to build both.

**Comment by tfcollins** [comment]
I would say xcode11 since we have builds in xcode10.X

**Comment by rgetz** [comment]
I think this is fixed with the existing pull request #294- so closing.
