### ISSUE TITLE
How to get attribute length or read it as a stream?

### ISSUE THREAD

**Issue by krsch** [analogdevicesinc/libiio#287]
I was trying to find a way to read an attribute as a C++ `std::string`, but could not find a way to either get the attribute length or read it sequentially (as a stream). It seems to be possible for at least network backend but this functionality is not exported in the library interface. Is it impossible to do for some backends or is it just considered unneeded?

**Comment by rgetz** [comment]
The best place for answers like this is on ADI's Engineerzone : https://ez.analog.com/linux-device-drivers/linux-software-drivers.

I posted it here : https://ez.analog.com/linux-device-drivers/linux-software-drivers/f/q-a/114038/how-to-get-attribute-length-or-read-it-as-a-stream
