### ISSUE TITLE
Missing values in pkg-config file

### ISSUE THREAD

**Issue by linkmauve** [analogdevicesinc/libiio#29]
In libiio.pc, libdir, sharedlibdir and includedir are empty when built with the default options, leading to pkg-config giving broken options to gcc.

**Comment by pcercuei** [comment]
Ooops, looks like I broke it recently (in commit https://github.com/analogdevicesinc/libiio/commit/0e2bce7). I will fix it on monday, thanks!

**Comment by pcercuei** [comment]
Fixed in https://github.com/analogdevicesinc/libiio/commit/f7de353.
