### ISSUE TITLE
Error when connecting to IIOd over IPv6

### ISSUE THREAD

**Issue by jonkerj** [analogdevicesinc/libiio#296]
When I try to use IIO to connect to a IPv6 resolvable host, I get errors when libiio tries to create a context for me:

```
jorik@zinc:~/iio/src$ host my.host.name
my.host.name has address 172.21.42.19
my.host.name has IPv6 address 2001:1540:xxxx

jorik@zinc:~/iio/src$ tests/iio_info -n my.host.name
Library version: 0.18 (git tag: 4e22517)
Compiled with backends: local xml ip usb serial
ERROR: Unable to lookup interface of IPv6 address
Unable to create IIO context: No such device or address
```

Looking through the sources, I find [these lines](https://github.com/analogdevicesinc/libiio/blob/v0.18/network.c#L1534-L1549) responsible for the error:

```
	if (res->ai_family == AF_INET6) {
		struct sockaddr_in6 *in = (struct sockaddr_in6 *) res->ai_addr;
		char *ptr;
		inet_ntop(AF_INET6, &in->sin6_addr,
				description, INET6_ADDRSTRLEN);

		ptr = if_indextoname(in->sin6_scope_id, description +
				strlen(description) + 1);
		if (!ptr) {
			ret = -errno;
			ERROR("Unable to lookup interface of IPv6 address\n");
			goto err_free_description;
		}

		*(ptr - 1) = '%';
	}
```

I have added code to display the value of `in->sin6_scope_id`, which is 0 in my case. 

I did some [reading](http://man7.org/linux/man-pages/man7/ipv6.7.html), and `sin6_scope_id` is described as: "an ID depending on the scope of the address.  It is new in Linux 2.4. Linux supports it only for link-local addresses, in that case `sin6_scope_id` contains the interface index."

So, unconditionally trying to resolve the interface index and failing hard on this renders this code unusable for connecting to non-linklocal IPv6 addresses. It might work when using link-local (ie, through Avahi), though.

I'd like submit a PR to fix this, but I am not really sure what's the right strategy. To me, it looks like only trying to resolve non-zero interface indices should do it. But the comment in a821c406f32655affbe614b5ccb1fed1990b4e55, the commit that introduced interface resolving states that it is required to properly clone a context. @pcercuei, could you maybe comment on this?

**Comment by pcercuei** [comment]
I only ever tried IPv6 on a local network, so maybe this step is simply not required with global addresses.
