### ISSUE TITLE
iio_channel_attr read segmentation fault

### ISSUE THREAD

**Issue by owner01** [analogdevicesinc/libiio#299]
When calling a function such as iio_channel_attr_read_double with a NULL pointer this will result in a segmentation fault, this is because in line 124 of utilities.c:
*val = value;
The value of the sensor will be written to the location 0x0 which will result in an segmentation fault.

A simple solution would be to check if the address is not an null pointer.

**Comment by mhennerich** [comment]
Please see discussion here:
https://github.com/analogdevicesinc/libiio/pull/278
