### ISSUE TITLE
Wrong argument help in example.

### ISSUE THREAD

**Issue by dimasad** [analogdevicesinc/libiio#302]
In the examples/dummy-iiostream.c example, the help for the read method is 2 read, 3 read raw, while the order of the enum makes it 2 read raw, 3 read.

**Comment by rgetz** [comment]
yeah, it looks like:

https://github.com/analogdevicesinc/libiio/blob/master/examples/dummy-iiostream.c#L159
```
	printf("  -r\tread method (default 0 pointer, 1 callback, 2 read, 3 read raw)\n");
```

and 
https://github.com/analogdevicesinc/libiio/blob/master/examples/dummy-iiostream.c#L94
```
enum {
	BUFFER_POINTER,
	SAMPLE_CALLBACK,
	CHANNEL_READ_RAW,
	CHANNEL_READ,
	MAX_READ_METHOD,
};
```

is in the incorrect order. I will update, and check the others.

Thanks for pointing out.

**Comment by rgetz** [comment]
added a fix - should be resolved on the next release.

**Comment by rgetz** [comment]
closing this - since the PR/merge is in progress.

Thanks again for pointing this out.
