### ISSUE TITLE
printf types in dummy-iiostream example not platform independent

### ISSUE THREAD

**Issue by dimasad** [analogdevicesinc/libiio#303]
The examples/dummy-iiostream.c printf types are not platform independent, and do generate compilation error in the armhf architecture, as in the BeagleBone.

**Comment by rgetz** [comment]
we build this on Zynq, and cross compile for zynq all time time...

```
root@analog:~# gcc  -v -E -x c++ -dD /dev/null 
Using built-in specs.
COLLECT_GCC=gcc
Target: arm-linux-gnueabihf
```

what errors are you getting?

**Comment by dimasad** [comment]
Sorry, I did not get compilation errors, but build-time warnings. When I ran the program, I got weird numbers. Right now I do not have access to the exact messages, but when I get hold of my BBB again I can post it here, if you want.

**Comment by pcercuei** [comment]
The ```BUFFER_POINTER``` and ```CHANNEL_READ``` cases uses ```%d``` and ```%ld``` tokens for ```int16_t``` and ```int64_t``` values, they should use ```"%" PRId16``` and ```"%" PRId64``` respectively.
