### ISSUE TITLE
Use space chars in iio.py

### ISSUE THREAD

**Issue by eblot** [analogdevicesinc/libiio#311]
It would be nice to follow PEP8 and replace tabs with space chars in `iio.py`

https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces

**Comment by pcercuei** [comment]
We can't really change that now, because it would trash the whole git history of the file... (you wouldn't be able to git-blame afterwards)

**Comment by julienmalik** [comment]
Reading https://eev.ee/blog/2016/06/04/converting-a-git-repo-from-tabs-to-spaces/ :

`git blame -w` ignores whitespace only changes

my 2 cents...

**Comment by rgetz** [comment]
Yeah, command line git blame, most git UI support it...
https://github.com/gitextensions/gitextensions/issues/4915

the html interface (github) does not (that I can tell).

**Comment by pcercuei** [comment]
Well PEB8 only says that spaces are the *preferred* indentation method, and that we shouldn't mix spaces with tabs, which we don't.

**Comment by eblot** [comment]
It is not mandatory you are right. However tab usage is quite sparse with Python community (ex: https://ukupat.github.io/tabs-or-spaces/), so it is definitely not easy to work with Python projects where pretty much all Python modules follow the same (space) rule except `libiio`. 
It is not a big deal, but it definitely does not help to write patches for it, IMHO.

**Comment by rgetz** [comment]
yeah, I ran into a problem with vim recently - any file with the suffix of ".py" it assumes it wants to be indented with spaces. I needed to rename the file in order it would keep the tabs....

Found this [here](https://www.i-programmer.info/news/99-professional/10049-tabs-or-spaces-one-billion-files-later-an-answer.html) Spaces "win" for python.
![image](https://user-images.githubusercontent.com/1017869/73388778-db51e780-42a0-11ea-86c1-7c51baaf2261.png)

**Comment by pcercuei** [comment]
Keep in mind you need 4 or 8 spaces for one tab ;)

**Comment by rgetz** [comment]
@pcercuei : it's 184 lines, so, the file size would increase by 552 bytes... (tabs would be removed, and replaced by 4 spaces). I think that is something we can do (if we want) :)

**Comment by rgetz** [comment]
I am in process of adding black/flake-8 processing as part of PR #413 - so we will track things there...

If you have any comments - please comment there.
