### ISSUE TITLE
libiio-0.18/tests/iio_attr.c:529: bad test ?

### ISSUE THREAD

**Issue by dcb314** [analogdevicesinc/libiio#325]
libiio-0.18/tests/iio_attr.c:529:11: warning: logical 'and' of mutually exclusive tests is always false [-Wlogical-op]

Source code is

   if (wbuf && !wbuf)

**Comment by rgetz** [comment]
https://github.com/analogdevicesinc/libiio/blame/master/tests/iio_attr.c#L529

yeah, that looks like my issue. Thanks for pointing out.

**Comment by rgetz** [comment]
PR #340 is in process to fix this - so closing this here.

Thanks for the bug report.
