### ISSUE TITLE
Python not found in cmake anymore

### ISSUE THREAD

**Issue by tfcollins** [analogdevicesinc/libiio#327]
Reported: https://ez.analog.com/linux-device-drivers/linux-software-drivers/f/q-a/119611/linux-libiio-python-bindings

I believe this is the problem: https://github.com/analogdevicesinc/libiio/blob/master/bindings/python/CMakeLists.txt#L4 and older cmake versions. The FindPython module doesn't seem to exist prior to cmake 3.12.

Bumping cmake versions would cause more issues since Ubuntu 18.04 ships with CMake 3.10.

**Comment by matejk** [comment]
This can be fixed by using different module for different CMake versions.

I'll provide pull request.

**Comment by rgetz** [comment]
This was merged into master - so closing this.
