### ISSUE TITLE
No Pluto found with libiio on Ubunutu 18.04

### ISSUE THREAD

**Issue by patel999jay** [analogdevicesinc/libiio#331]
No pluto/context has been found on Ubunutu 18.04. it found pluto on usb. I built libiio from source but still same problem.

 `jay@jay-MS-7885:~$ iio_info -s
Library version: 0.18 (git tag: v0.18)
Compiled with backends: local xml ip
No contexts found.`

**Comment by pcercuei** [comment]
It says ```compiled with backends: local xml ip```, so it was not compiled with the USB backend.

**Comment by patel999jay** [comment]
I already had a look on the source code and CMakeLists.txt, but didn't find a solution. Is the 'WITH_IIOD_USBD' option is only available under certain conditions ?

**Comment by pcercuei** [comment]
You need the ```libusb-1.0.0-dev``` package installed, then the option ```WITH_USB_BACKEND``` should be available.

**Comment by patel999jay** [comment]
Thanks. I had already installed `libusb-dev` And build this from source but not sure why it didn’t build with usb backend support.

**Comment by pcercuei** [comment]
Libiio uses libusb-1.0, the ```libusb-dev``` is for libusb-0.x, you are not the first one to fall for this trap, believe me ;)
