### ISSUE TITLE
how to send IQ data using tx1 and rx1 and tx2 and rx2

### ISSUE THREAD

**Issue by mustaphahaydar** [analogdevicesinc/libiio#34]
HI,

I use AD-FMComms2-EBZ platforme with ad9361 and Zedboard, controled by MATLAB windows. I send IQ data using TXRX and it work well.
i tried to send IQ data using tx1rx1 and tx2rx2 (MIMO 2*2) with different frequency on each txrx.  How can i reconfigure ad9361.cfg to succeded this communication.

Thank you
Regards

**Comment by mhennerich** [comment]
Hi,

Please ask these kindof questions here: 
https://ez.analog.com/community/linux-device-drivers/linux-software-drivers.

Both RX share the same LO, just like both TX share the same TX LO.
In addition both RX paths also share the same baseband rate.
Same applies for TX as well.

-Michael
