### ISSUE TITLE
Why is there no `iio_device_get_buffer` method?

### ISSUE THREAD

**Issue by lmoellendorf** [analogdevicesinc/libiio#349]
At the moment I have to keep references to the buffer myself for each IIO device. I wonder why there is no such API:

```c
struct iio_buffer* iio_device_get_buffer(const struct iio_device *dev)
```

**Comment by pcercuei** [comment]
Hi,

When you create the buffer, you can use ```iio_device_set_data``` to have it memorized inside the iio_device structure, then you can retrieve the pointer with ```iio_device_get_data```.

**Comment by lmoellendorf** [comment]
Thank you. This solves this issue for me.
