### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/libiio#350]
This was pointed out in : 
https://bugzilla.redhat.com/show_bug.cgi?id=1426465

In all of the libiio *.c files (backend.c  buffer.c  channel.c  context.c  device.c  iiod-client.c  local.c  lock.c  network.c  scan.c  serial.c  sort.c  usb.c  utilities.c  xml.c), it's indicated:
```
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
```
In mainpage.dox it indicates:
```
Libiio has been developed and is released under the terms of the GNU Lesser General Public
License, version 2. 
```
which is missing the "any later version". Same for the README.md file.

Also, the utilities, which are in the `./test` directory, aren't a library, and LGPL doesn't really make sense for those applications. Same for the `./examples` directory. Section 2a of the LGPL states:
https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html
```
a) The modified work must itself be a software library.
```

I would propose that:
-  I fix the README and Dox to match the license in the code (which I will do).
- the files in the ./test directory be updated to "GPLv2 or any later version"
- the files in the ./examples directory be updated to "GPLv2 or any later version"

I just need everyone's OK for 2 & 3 (if anyone doesn't answer, I won't do it).

Authors of c files in the ./test directory: @johnnykv @julienmalik @larsclausen @lucasrangit @mtitinger @mfornero @mhei @mhennerich @pcercuei @rgetz : I need your permission to do this.

Authors of c files in the ./examples directory @dNechita @dimasad @geertu @larsclausen @lucasrangit @mhennerich @pcercuei @SrikanthPagadarai @tfcollins : I need your permission to do this. 

Thanks

**Comment by johnnykv** [comment]
Permission hereby given.

**Comment by mhennerich** [comment]
Hereby approved

**Comment by geertu** [comment]
Approved.

**Comment by dNechita** [comment]
I'm OK with it

**Comment by pcercuei** [comment]
Sure, approved.

**Comment by mtitinger** [comment]
Ok with me,
cheers!
M.

**Comment by larsclausen** [comment]
ok

**Comment by dimasad** [comment]
I agree.

**Comment by lucasrangit** [comment]
OK

**Comment by mfornero** [comment]
Approved

**Comment by tfcollins** [comment]
Approve

**Comment by SrikanthPagadarai** [comment]
I'm ok with it.

**Comment by mhei** [comment]
Sure I agree, thanks for digging into this!

**Comment by rgetz** [comment]
So that just leaves @julienmalik - I will reach out via email and get permission for this patch:

https://github.com/analogdevicesinc/libiio/commit/ac8debcedda20a7713bfa13411d7cd916dc5295a#diff-819036057d9192362290c6c2235e15ab

**Comment by julienmalik** [comment]
I hereby agree on the license change to "GPLv2 or any later version".

**Comment by rgetz** [comment]
Thanks everyone - will work on this later today.

**Comment by rgetz** [comment]
closing this since there is a pull request in progress.

**Comment by rgetz** [comment]
@dNechita pointed out the binding examples needed the same love.

libiio/bindings/python/examples were all done by @pcercuei
libiio/bindings/csharp/examples were all done by @pcercuei 
libiio/bindings/matlab was done by @tfcollins and @radhermit (but are weird since they are licensed under the ADI-BSD license...)

I know that @pcercuei and @tfcollins said it was OK above, that leaves Tim...

Thanks
-Robin

**Comment by radhermit** [comment]
> I know that @pcercuei and @tfcollins said it was OK above, that leaves Tim...

It's fine by me.

**Comment by rgetz** [comment]
Thanks - will update.
