### ISSUE TITLE
Updating context when new device appears

### ISSUE THREAD

**Issue by xhpohanka** [analogdevicesinc/libiio#36]
For some purposes `iio_sysfs_trigger` module is quiet usable. New triggers `sysfstrigX` are added after writing X into `iio_sysfs_trigger/add_trigger`. Unfortunately it seems that there is no way to update existing context with new trigger devices after it was created.

**Comment by rgetz** [comment]
I think this has moved to https://marc.info/?l=linux-iio&m=157590518011821&w=2 so closing this request. @pcercuei - that make sense to you?
