### ISSUE TITLE
Deprecate libiio MATLAB bindings

### ISSUE THREAD

**Issue by tfcollins** [analogdevicesinc/libiio#363]
We have been on the MathWorks API for quite awhile and is time to deprecate these

**Comment by rgetz** [comment]
Cool - can you send a PR?

**Comment by tfcollins** [comment]
Getting some info from MathWorks if they still need that wrapper header

**Comment by rgetz** [comment]
should we just leave as is for the next release (which is happening ~this week?) or rm things?

**Comment by tfcollins** [comment]
Leave it for now. Don't want to rush this and break MW support

**Comment by rgetz** [comment]
Looks good - I will close this, and follow up anything on the PR
