### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [analogdevicesinc/libiio#4]
I have looked at a few source files for your current software. I have noticed that some checks for return codes are missing.

Would you like to add more error handling for return values from functions like the following?
- [pthread_mutex_lock](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_lock.html "lock a mutex") ⇒ [network_lock](https://github.com/analogdevicesinc/libiio/blob/88318d2c46cbdd32390dd98800168d0a214fab01/network.c#L175)
- [pthread_cond_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_init.html "initialize condition variables") ⇒ [open_dev_helper](https://github.com/analogdevicesinc/libiio/blob/b7fa23369147d9190024f43951d0c7955f6931c3/iiod/ops.c#L590)

**Comment by pcercuei** [comment]
Handling return codes is not useful, for several reasons:
* pthread_cond_init never returns an error code, and pthread_mutex_lock will only fail if the mutex is not initialized or already locked by the same thread, which simply cannot happen in the current code.
* those synchronization mechanisms are mostly here to prevent crashes on the server side, if two threads share the same IIO context. But that doesn't avoid all kind of errors (e.g. one thread closes the device opened by the other one, then you get errors). It is therefore highly recommended to use one IIO context per thread.

**Comment by elfring** [comment]
I guess that the probability for failures by calls of functions from the POSIX thread API is not really known here.

I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?
