### ISSUE TITLE
problems when I try to install pyadi-iio with python 3.5.2

### ISSUE THREAD

**Issue by JanVerlinden** [analogdevicesinc/libiio#419]
Is python 3.5.2. not supported? I have the impression that I need python 3.6?  Or is there a simple work around to use pyadi-iio in python 3.5.2?

**Comment by rgetz** [comment]
are you interested in libiio (this repo) or peyote (pyadi-iio) which is answered [here](https://github.com/analogdevicesinc/pyadi-iio/issues)

**Comment by JanVerlinden** [comment]
sorry, I was talking about pyadi-iio
