### ISSUE TITLE
IPv6 on Windows

### ISSUE THREAD

**Issue by pcercuei** [analogdevicesinc/libiio#46]
Libiio does not support IPv6 on Windows, while it does on Linux.

**Comment by gvanem** [comment]
For Windows, supporting IPv6 is very easy:
```diff
--- a/network.c 2022-04-04 10:17:44
+++ b/network.c 2022-04-04 14:50:30
@@ -22,6 +22,7 @@
 #ifdef _WIN32
 #include <winsock2.h>
 #include <ws2tcpip.h>
+#include <netioapi.h>  /* if_indextoname() */
 #else
```

**Comment by pcercuei** [comment]
That bug is from 6 years ago :)
But if it's that simple, I'll see if I can add it.

**Comment by pcercuei** [comment]
@gvanem see PR #828.
Can I add your Suggested-by to the commit?

**Comment by gvanem** [comment]
> Can I add your Suggested-by to the commit?

Sure.
