### ISSUE TITLE
Libiio release for Windows

### ISSUE THREAD

**Issue by damercer** [analogdevicesinc/libiio#47]
Is the Windows installer release for 32 or 64 bits?

If it is for 64 bits, it would be helpful if the file name indicated that.
Also if it is for 64 bits, would it be possible for you to provide a 32 bit version as well?
( Use will be will be with 32 bit Python ).

Thanks

**Comment by pcercuei** [comment]
The Windows installer is for both 32-bit and 64-bit versions.
On 64-bit systems, it will install the 32-bit version too.

**Comment by damercer** [comment]
So there are two different .dll files? What are their names and where are they installed?
Because the one I found seems to be for 64 bits. 32 bit Python says it is not a WIN32 file.

Thanks

**Comment by pcercuei** [comment]
C:\Windows\System32\libiio.dll is the 64-bit version
C:\Windows\SysWOW64\libiio.dll is the 32-bit version

Can I close this bug?

**Comment by damercer** [comment]
Python 32 bit seems to find the "right" version of libiio.dll but it fails to properly load see issue #48.
However I don't see a file named libiio.dll in C:\Windows\SysWOW64\?

**Comment by pcercuei** [comment]
It might have been added after the version 2015.02. Try with a nighty build of libiio:
https://ci.appveyor.com/project/analogdevicesinc/libiio/build/artifacts?branch=master
