### ISSUE TITLE
Add better readme for python bindings

### ISSUE THREAD

**Issue by tfcollins** [analogdevicesinc/libiio#479]
Python bindings simply import the root readme which looks quite awkward on pypi. It should have a specific one.

**Comment by rgetz** [comment]
@cristi-iacob is this something you can add? I think it is just a README.md file its looking for.

**Comment by rgetz** [comment]
I think this is causing some warnings in the AppVeyor logs too...
```
writing manifest file 'libiio.egg-info\SOURCES.txt'
1422 warning: sdist: standard file not found: should have one of README, README.rst, README.txt, README.md
```

**Comment by cristi-iacob** [comment]
I will take a look on this.

**Comment by rgetz** [comment]
I think we are working on this in #483, so will close here.
