### ISSUE TITLE
sudo make install leaves files in ./build directory as root

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/libiio#55]
mkdir build
cd build
cmake .. && make && sudo make install

then:

analog@imhotep:~/github/libiio/build$ rm * -rf
rm: cannot remove 'build/lib.linux-x86_64-2.7/iio.py': Permission denied
analog@imhotep:~/github/libiio/build$ ls -l ./build/lib.linux-x86_64-2.7/
total 24
-rw-r--r-- 1 root root 24168 Oct 27 12:20 iio.py

?

**Comment by pcercuei** [comment]
Fixed. Thanks!
