### ISSUE TITLE
Release tag format changed in (v)0.21

### ISSUE THREAD

**Issue by mhennerich** [analogdevicesinc/libiio#558]
All previous releases used to have a 'v' as prefix.
such as v0.19, latest release is only called 0.21.
This causes some hick ups in buildroot. These can be fixed. 
But a consistent naming schema would be desired.

**Comment by dNechita** [comment]
It was a mistake of mine, sorry about that.

Would it make sense to create a git tag "v0.21" which would point to the same SHA commit as tag "0.20"? This won't fix the github release though.

**Comment by rgetz** [comment]
yes - if you can do that - it would fix things on some of the build systems.

**Comment by mhennerich** [comment]
For buildroot the issue was that the build artifact name changed.
Just creating a additional tag doesn't solve this. Anyways the fix for buildroot is easy.

**Comment by rgetz** [comment]
So, this is Ok to be closed?

**Comment by mhennerich** [comment]
Yes close
