### ISSUE TITLE
missing debian dsc and rpm spec files

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/libiio#58]
Before I create these - does anyone have them already? Shouldn't they be in github somewhere?

Thanks
-Robin

**Comment by pcercuei** [comment]
The .deb files are in the "deb" branch. They used to be included in the repository until the Debian package was accepted uptream and the maintainer told me to drop the debian folder from our tree.

**Comment by rgetz** [comment]
I don't see a .dsc file, or a .dsc files is build from those? (ISorry - 'm not a debian package person).

Any any volunteers for the spec file?

**Comment by pcercuei** [comment]
The .dsc is built from those.

**Comment by rgetz** [comment]
Thanks. 

I will try to follow the directions at:
https://www.debian.org/doc/manuals/maint-guide/build.en.html
