### ISSUE TITLE
iio_readdev corrupts the data when using auto detection 

### ISSUE THREAD

**Issue by dernasherbrezon** [analogdevicesinc/libiio#583]
Run iio_readdev in the auto detection mode (i.e. "-a"):

```
#: ./iio_readdev -a -s 2 cf-ad9361-lpc
Using auto-detected IIO context at URI "usb:20.10.5"
??????%
```

All data produced to stdout. Thus the message "Using auto-detected IIO context at URI "usb:20.10.5"" corrupts the output.

**Comment by rgetz** [comment]
Yeah - if you pipe this to something else - it will garble things. 

For now - point to the specific url, "`-u usb:20.10.5`" rather than "`-a`"

Thanks for the bug report - I will fix, and add a test case.
