### ISSUE TITLE
library not loaded on macos 10.15

### ISSUE THREAD

**Issue by Scottpedia** [analogdevicesinc/libiio#587]
I was following this [guide](https://wiki.analog.com/resources/tools-software/linux-software/iio_oscilloscope#macos)  to install IIO Oscilloscope on macos 10.15. I got this when I tried to launch osc from the terminal.
```shell
dyld: Library not loaded: @rpath/iio.framework/Versions/0.17/iio
  Referenced from: /Library/Frameworks/ad9361.framework/Versions/0.2/ad9361
  Reason: image not found
Abort trap: 6
``` 

I have installed both iio0.17, iio0.21 and libad9361 with pkg files.

**Comment by tfcollins** [comment]
This issue isn't related to libiio. Please open an issue in the IIO-Oscilloscope repo.

-Travis
