### ISSUE TITLE
 Reproducible Builds

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/libiio#591]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=970498

**Comment by tfcollins** [comment]
Anyway for us to test this?

**Comment by rgetz** [comment]
make two builds - make sure they are identical ?

**Comment by mhennerich** [comment]
@dNechita  can you apply the patch from here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=970498

and test reproducibility?

**Comment by dNechita** [comment]
Yes, I will test.

**Comment by dNechita** [comment]
I've tested with the changes in the patch
 What the patch does is that allows setting the date during the cmake step. So, if you want to reproduce an identical build with a yesterday build, all you need is to set an environment variable with the yesterday date and then do the build.
Then, the man pages will be identical.

**Comment by dNechita** [comment]
The idea is to add the changes in the patch to libiio, right?
If so, I'm not sure how to apply the patch (which seems to be a debian diff sort of thing) in order the preserve the original author. Any suggestions?

**Comment by rgetz** [comment]
I think it is just : 
`git commit --author="Author Name <email@address.com>"`

but you need their permission first. The DCO is per author, and we won't accept anything without a signed-off-by by the original author.

-Robin

**Comment by lamby** [comment]
Added PR. :+1:

**Comment by rgetz** [comment]
Thanks for the PR
