### ISSUE TITLE
Eliminate variable shadowing in local.c 

### ISSUE THREAD

**Issue by msporcich** [analogdevicesinc/libiio#611]
In local.c, there are two instances of variable shadowing which cause the build to fail when compiling with flag 
`-Werror=shadow 
`

In local_close()
`  error: declaration of ‘i’ shadows a previous local [-Werror=shadow]
`
In get_short_attr_name()
`error: declaration of ‘len’ shadows a previous local [-Werror=shadow]
`

**Comment by msporcich** [comment]
Forked with a proposed resolution.  I'm interested in getting any comments and then signoff so that I may issue a pull request.  Thanks.

**Comment by commodo** [comment]
the change looks reasonable to me
feel free do a PR targeting our master;

thanks
Alex

**Comment by rgetz** [comment]
Only question is should we add `-Werror=shadow` all the time? (for gcc)

Nominally it's `-Wall -Wextra -Wno-unused-parameter -Wpedantic -std=c99`

**Comment by rgetz** [comment]
closing this.
