### ISSUE TITLE
Master Status Failing and Trojan

### ISSUE THREAD

**Issue by rhildreth** [analogdevicesinc/libiio#623]
The master GitHub status for Windows shows failing.  Also Win 10 Security flags the install file as Trojan:Win32/Spursint.F!cl.

I want to install GNURadio v3.8.1.0/v1.7 (py2.7) and I'm assuming I need to install libiio first.

Thanks for you help.

Ron

**Comment by tfcollins** [comment]
Artifacts from appveyor are not signed so anti-viruses overreact. We recommend starting with a release from the releases page.

-Travis
