### ISSUE TITLE
Support for rescanning/reopening devices in iiod

### ISSUE THREAD

**Issue by yaperez-anssi** [analogdevicesinc/libiio#640]
I'm currently playing with a PlutoSDR where I want to later expose some MMIO registers (from the PL/FPGA part). Since it seems that the PlutoSDR heavily relies on the IIO subsystem I'm trying to craft an IIO kernel module for that, so it can get exposed by libiio/iiod accross USB or network.

Right now I'm testing the driver using a kernel module so I don't have to rebuild and reflash the image (even to RAM) everytime.

I can load the kernel module and create a new IIO_SW_DEVICE device node which locally appears on the PlutoSDR, but is not exposed by iiod. I guess that's because iiod would need to rescan the devices, or be restarted. Unfortunately it seems that on the PlutoSDR it's not possible to restart iiod (it'll disappear from the network), so having a way to ask iiod for a rescan would be really nice.

**Comment by rgetz** [comment]
This really isn't easy with the current architecture. I did have a branch that did something similar (looking for changes in sysfs), but it's complicated - since you can have multiple clients, and the backing iiod needs to be the same as the the client that is attached to it.

Your concept works in the simple use case, but not in the complicated ones (multiple connected clients)...

Let me think about it some more.

**Comment by yaperez-anssi** [comment]
Good point, the clients might need to be notified so they can rescan themselves or something. I have to admit my issue might be specific to the PlutoSDR, because usually you might just want to restart the daemon (and maybe the clients), but unfortunately I can't do that.

**Comment by rgetz** [comment]
There is no "notification" in the existing libiio implementation. All the client can do is close the context, and re-open things if it different. That's the way that the current implementation is architected. I think the tests I was doing would function, but would require a lot more testing... Let me think about it a bit more...

**Comment by rgetz** [comment]
This is sort of a dup of #911 now.

**Comment by yaperez-anssi** [comment]
Yes indeed, thanks for the pointer, I'll subscribe to that one.

**Comment by rgetz** [comment]
This can be closed now (I can't anymore).

**Comment by yaperez-anssi** [comment]
Closing because duplicate of #911
