### ISSUE TITLE
dummy-iostream issue

### ISSUE THREAD

**Issue by Mezzano** [analogdevicesinc/libiio#656]
Hello,

I'm testing libiio 0.21 with the mpu9250.

When running the dummy-iostream.c code, I can't destroy buffers:

* Destroying buffers
ERROR: Error during buffer disable: Device or resource busy (16)

The dummy-iostream.c example also breaks when trying to enable the temp channel (which is not indexed but listed in the scan elements of sysfs). 

Kind regards

**Comment by pcercuei** [comment]
@Mezzano could you give us a dump of the IIO context (with `iio_genxml`)?

**Comment by rgetz** [comment]
closing, as there was no followup
