### ISSUE TITLE
[docs] dead links

### ISSUE THREAD

**Issue by JelmerT** [analogdevicesinc/libiio#670]
The links in the readme to the releases for macOS 10.12 and 10.14 are dead.

May I suggest removing that whole table and just linking to the latest release here on github, that should prevent a lot of confusion.

**Comment by pcercuei** [comment]
I think swdownloads.analog.com is down, so that's probably just temporary.

**Comment by tfcollins** [comment]
Builds are being shifted towards Azure including artifacts. We'll update the links to point to Azure.
