### ISSUE TITLE
iiod: dropping buffer refills

### ISSUE THREAD

**Issue by jcn9k** [analogdevicesinc/libiio#70]
I have a iio ADC driver using DMA to transfers.
When the userspace iio software is running on our embedded system using the local interface everything looks good. However using the network interface via iiod results in missing buffers, we are losing about a third of all data. Data is being read using iio_buffer_refill.

I'm digging into it to see if I can find the problem, but I've added some debug stated to iiod and can see iiod refilling at roughly the correct rate. But it is not issuing an writefd_io op for every refill. Sample rate is 24000sps with 4bytes per sample with a single channel.

Below is a log with some the additional messages inserted and timestamps added.

If anyone has any pointers on where to look that'd help.

Thanks
Phil

1480414079.731135920 DEBUG: Mask[0] = 0x00000001
1480414079.731309450 DEBUG: writefd_io: 2
1480414079.733963770 DEBUG: Waiting for completion...
1480414081.280262490 DEBUG: iio_buffer_refill: 40000
1480414081.280377950 DEBUG: writefd_io: 6
1480414081.280414930 DEBUG: writefd_io: 9
1480414081.280777680 DEBUG: writefd_io: 27731
1480414081.292457200 DEBUG: writefd_io: 12269
1480414081.296015000 DEBUG: Exiting rw_buffer with code 0
1480414081.301273900 DEBUG: Waiting for completion...
1480414081.974149370 DEBUG: iio_buffer_refill: 40000
1480414081.974287560 DEBUG: writefd_io: 6
1480414081.974333820 DEBUG: writefd_io: 9
1480414081.974646960 DEBUG: writefd_io: 36491
1480414081.976232780 DEBUG: writefd_io: 3509
1480414081.976325270 DEBUG: Exiting rw_buffer with code 0
1480414081.976500800 DEBUG: iio_buffer_refill: 40000
1480414081.982892750 DEBUG: Waiting for completion...
1480414082.656784750 DEBUG: iio_buffer_refill: 40000
1480414082.656931800 DEBUG: writefd_io: 6
1480414082.656974310 DEBUG: writefd_io: 9
1480414082.657551100 DEBUG: writefd_io: 39411
1480414082.658288270 DEBUG: writefd_io: 589
1480414082.658591230 DEBUG: Exiting rw_buffer with code 0
1480414082.669794630 DEBUG: Waiting for completion...
1480414083.339325110 DEBUG: iio_buffer_refill: 40000
1480414083.339503590 DEBUG: writefd_io: 6
1480414083.339584880 DEBUG: writefd_io: 9
1480414083.340001230 DEBUG: writefd_io: 40000
1480414083.340255160 DEBUG: Exiting rw_buffer with code 0
1480414083.340311110 DEBUG: iio_buffer_refill: 40000
1480414083.346527180 DEBUG: Waiting for completion...
1480414084.021636260 DEBUG: iio_buffer_refill: 40000
1480414084.021750630 DEBUG: writefd_io: 6
1480414084.021787380 DEBUG: writefd_io: 9
1480414084.022201650 DEBUG: writefd_io: 40000
1480414084.022271250 DEBUG: Exiting rw_buffer with code 0
1480414084.022478610 DEBUG: iio_buffer_refill: 40000
1480414084.028074920 DEBUG: Waiting for completion...
1480414084.704703950 DEBUG: iio_buffer_refill: 40000
1480414084.704878260 DEBUG: writefd_io: 6
1480414084.704958600 DEBUG: writefd_io: 9
1480414084.705379680 DEBUG: writefd_io: 40000
1480414084.707134320 DEBUG: Exiting rw_buffer with code 0
1480414084.716438780 DEBUG: Waiting for completion...
1480414085.387262830 DEBUG: iio_buffer_refill: 40000
1480414085.387453850 DEBUG: writefd_io: 6
1480414085.387531730 DEBUG: writefd_io: 9
1480414085.388030340 DEBUG: writefd_io: 40000
1480414085.388278010 DEBUG: Exiting rw_buffer with code 0
1480414085.388335590 DEBUG: iio_buffer_refill: 40000
1480414085.395464210 DEBUG: Waiting for completion...
1480414086.069969010 DEBUG: iio_buffer_refill: 40000
1480414086.070155530 DEBUG: writefd_io: 6
1480414086.070244510 DEBUG: writefd_io: 9
1480414086.070677660 DEBUG: writefd_io: 40000
1480414086.070921860 DEBUG: Exiting rw_buffer with code 0
1480414086.071049370 DEBUG: iio_buffer_refill: 40000
1480414086.076090770 DEBUG: Waiting for completion...
1480414086.752683200 DEBUG: iio_buffer_refill: 40000
1480414086.752862950 DEBUG: writefd_io: 6
1480414086.752945150 DEBUG: writefd_io: 9
1480414086.753366680 DEBUG: writefd_io: 40000
1480414086.756252300 DEBUG: Exiting rw_buffer with code 0
1480414086.762326660 DEBUG: Waiting for completion...
1480414087.435226630 DEBUG: iio_buffer_refill: 40000
1480414087.435639540 DEBUG: writefd_io: 6
1480414087.435868710 DEBUG: writefd_io: 9
1480414087.436669110 DEBUG: writefd_io: 40000
1480414087.436972790 DEBUG: Exiting rw_buffer with code 0
1480414087.437151730 DEBUG: iio_buffer_refill: 40000
1480414087.442761350 DEBUG: Waiting for completion...
1480414088.117940800 DEBUG: iio_buffer_refill: 40000
1480414088.118122780 DEBUG: writefd_io: 6
1480414088.118203270 DEBUG: writefd_io: 9
1480414088.118643220 DEBUG: writefd_io: 40000
1480414088.118882800 DEBUG: Exiting rw_buffer with code 0
1480414088.118941380 DEBUG: iio_buffer_refill: 40000
1480414088.124553950 DEBUG: Waiting for completion...
1480414088.800740630 DEBUG: iio_buffer_refill: 40000
1480414088.800970840 DEBUG: writefd_io: 6
1480414088.801094010 DEBUG: writefd_io: 9
1480414088.801529020 DEBUG: writefd_io: 40000
1480414088.805805330 DEBUG: Exiting rw_buffer with code 0
1480414088.810474850 DEBUG: Waiting for completion...
1480414089.483238100 DEBUG: iio_buffer_refill: 40000
1480414089.483438790 DEBUG: writefd_io: 6
1480414089.483543730 DEBUG: writefd_io: 9
1480414089.483993380 DEBUG: writefd_io: 40000
1480414089.484236310 DEBUG: Exiting rw_buffer with code 0
1480414089.484323410 DEBUG: iio_buffer_refill: 40000
1480414089.490034700 DEBUG: Waiting for completion...
1480414090.166036690 DEBUG: iio_buffer_refill: 40000
1480414090.166215320 DEBUG: writefd_io: 6
1480414090.166322240 DEBUG: writefd_io: 9
1480414090.166762880 DEBUG: writefd_io: 40000
1480414090.166995030 DEBUG: Exiting rw_buffer with code 0
1480414090.178874890 DEBUG: Waiting for completion...
1480414090.848494810 DEBUG: iio_buffer_refill: 40000
1480414090.848668660 DEBUG: writefd_io: 6
1480414090.848747230 DEBUG: writefd_io: 9
1480414090.849154420 DEBUG: writefd_io: 40000
1480414090.849444490 DEBUG: iio_buffer_refill: 40000
1480414090.849552740 DEBUG: Exiting rw_buffer with code 0
1480414090.855519360 DEBUG: Waiting for completion...
1480414091.531277040 DEBUG: iio_buffer_refill: 40000
1480414091.531687490 DEBUG: writefd_io: 6
1480414091.531917580 DEBUG: writefd_io: 9
1480414091.532505700 DEBUG: writefd_io: 40000
1480414091.533834390 DEBUG: Exiting rw_buffer with code 0
1480414091.534367020 DEBUG: iio_buffer_refill: 40000
1480414091.538021220 DEBUG: Waiting for completion...
1480414092.213967260 DEBUG: iio_buffer_refill: 40000
1480414092.214376090 DEBUG: writefd_io: 6
1480414092.214600880 DEBUG: writefd_io: 9
1480414092.215716230 DEBUG: writefd_io: 40000
1480414092.216306750 DEBUG: Exiting rw_buffer with code 0
1480414092.223836580 DEBUG: Waiting for completion...
1480414092.896503800 DEBUG: iio_buffer_refill: 40000
1480414092.896913340 DEBUG: writefd_io: 6
1480414092.897137770 DEBUG: writefd_io: 9
1480414092.898306790 DEBUG: writefd_io: 40000
1480414092.898912660 DEBUG: Exiting rw_buffer with code 0
1480414092.899380190 DEBUG: iio_buffer_refill: 40000
1480414092.903443780 DEBUG: Waiting for completion...
1480414093.579241330 DEBUG: iio_buffer_refill: 40000
1480414093.579654950 DEBUG: writefd_io: 6
1480414093.579885350 DEBUG: writefd_io: 9
1480414093.580454240 DEBUG: writefd_io: 40000
1480414093.581535320 DEBUG: Exiting rw_buffer with code 0
1480414093.582294950 DEBUG: iio_buffer_refill: 40000
1480414093.586470720 DEBUG: Waiting for completion...
1480414094.262133880 DEBUG: iio_buffer_refill: 40000
1480414094.262553760 DEBUG: writefd_io: 6
1480414094.262775720 DEBUG: writefd_io: 9
1480414094.263782250 DEBUG: writefd_io: 40000
1480414094.264449090 DEBUG: Exiting rw_buffer with code 0
1480414094.269743120 DEBUG: Waiting for completion...
1480414094.944644180 DEBUG: iio_buffer_refill: 40000
1480414094.945053030 DEBUG: writefd_io: 6
1480414094.945282750 DEBUG: writefd_io: 9
1480414094.945859290 DEBUG: writefd_io: 40000
1480414094.946968660 DEBUG: Exiting rw_buffer with code 0
1480414094.947497740 DEBUG: iio_buffer_refill: 40000
1480414094.953180450 DEBUG: Waiting for completion...
1480414095.627421220 DEBUG: iio_buffer_refill: 40000
1480414095.627839040 DEBUG: writefd_io: 6
1480414095.628050960 DEBUG: writefd_io: 9
1480414095.628643220 DEBUG: writefd_io: 40000
1480414095.629559930 DEBUG: Exiting rw_buffer with code 0
1480414095.630182080 DEBUG: iio_buffer_refill: 40000
1480414095.633983770 DEBUG: Waiting for completion...
1480414096.310001650 DEBUG: iio_buffer_refill: 40000
1480414096.310443920 DEBUG: writefd_io: 6
1480414096.310645770 DEBUG: writefd_io: 9
1480414096.311203910 DEBUG: writefd_io: 40000
1480414096.311583760 DEBUG: Exiting rw_buffer with code 0
1480414096.319925020 DEBUG: Waiting for completion...
1480414096.993091290 DEBUG: iio_buffer_refill: 40000
1480414096.993481510 DEBUG: writefd_io: 6
1480414096.993703040 DEBUG: writefd_io: 9
1480414096.994273310 DEBUG: writefd_io: 40000
1480414096.995330170 DEBUG: Exiting rw_buffer with code 0
1480414096.995786580 DEBUG: iio_buffer_refill: 40000
1480414096.999675640 DEBUG: Waiting for completion...
1480414097.675426700 DEBUG: iio_buffer_refill: 40000
1480414097.675839310 DEBUG: writefd_io: 6
1480414097.676102900 DEBUG: writefd_io: 9
1480414097.676681090 DEBUG: writefd_io: 40000
1480414097.677667520 DEBUG: Exiting rw_buffer with code 0
1480414097.682118090 DEBUG: Waiting for completion...
1480414098.357995610 DEBUG: iio_buffer_refill: 40000
1480414098.358403350 DEBUG: writefd_io: 6
1480414098.358624570 DEBUG: writefd_io: 9
1480414098.359193280 DEBUG: writefd_io: 40000
1480414098.359486810 DEBUG: Exiting rw_buffer with code 0
1480414098.359882240 DEBUG: iio_buffer_refill: 40000
1480414098.369123740 DEBUG: Waiting for completion...
1480414099.040566370 DEBUG: iio_buffer_refill: 40000
1480414099.040679300 DEBUG: writefd_io: 6
1480414099.040714690 DEBUG: writefd_io: 9
1480414099.041119540 DEBUG: writefd_io: 40000
1480414099.041348200 DEBUG: iio_buffer_refill: 40000
1480414099.041412520 DEBUG: Exiting rw_buffer with code 0
1480414099.050088220 DEBUG: Waiting for completion...
1480414099.722953550 DEBUG: iio_buffer_refill: 40000
1480414099.723064550 DEBUG: writefd_io: 6
1480414099.723100030 DEBUG: writefd_io: 9
1480414099.723459790 DEBUG: writefd_io: 40000
1480414099.727739160 DEBUG: Exiting rw_buffer with code 0
1480414099.734795790 DEBUG: Waiting for completion...
1480414100.405539560 DEBUG: iio_buffer_refill: 40000
1480414100.405654870 DEBUG: writefd_io: 6
1480414100.405693610 DEBUG: writefd_io: 9
1480414100.406093070 DEBUG: writefd_io: 40000
1480414100.406323900 DEBUG: iio_buffer_refill: 40000
1480414100.406649530 DEBUG: Exiting rw_buffer with code 0
1480414100.412089390 DEBUG: Waiting for completion...
1480414101.088227290 DEBUG: iio_buffer_refill: 40000
1480414101.088336770 DEBUG: writefd_io: 6
1480414101.088374430 DEBUG: writefd_io: 9
1480414101.088741900 DEBUG: writefd_io: 40000
1480414101.088966870 DEBUG: iio_buffer_refill: 40000
1480414101.089650050 DEBUG: Exiting rw_buffer with code 0
1480414101.097322430 DEBUG: Waiting for completion...
1480414101.770986160 DEBUG: iio_buffer_refill: 40000
1480414101.771098320 DEBUG: writefd_io: 6
1480414101.771135770 DEBUG: writefd_io: 9
1480414101.771926810 DEBUG: writefd_io: 40000
1480414101.776741350 DEBUG: Exiting rw_buffer with code 0
1480414101.793312100 DEBUG: Waiting for completion...
1480414102.453826260 DEBUG: iio_buffer_refill: 40000
1480414102.454018010 DEBUG: writefd_io: 6
1480414102.454121590 DEBUG: writefd_io: 9
1480414102.454570730 DEBUG: writefd_io: 40000
1480414102.454709220 DEBUG: Exiting rw_buffer with code 0
1480414102.454983960 DEBUG: iio_buffer_refill: 40000

**Comment by pcercuei** [comment]
Hi,

Could you remove [this line](https://github.com/analogdevicesinc/libiio/blob/master/iiod/ops.c#L656) and see if it works better?

**Comment by jcn9k** [comment]
G'day Paul,

That seems to work. Each refill now has a correspond write in my log.

Thanks
Phil

**Comment by pcercuei** [comment]
Fixed it back in March, but it never made it to master. Thanks for the reminder!
