### ISSUE TITLE
Windows on ARM, Support?

### ISSUE THREAD

**Issue by sidd-kishan** [analogdevicesinc/libiio#705]
Please let us know when can we have an ARM64 version for Windows on ARM OS. We can help you test We have Windows on Rasberry Pi setup. Please pursue it we at Windows on Rasberry Pi community will be glad to extend support in testing your drivers and tools for ARM64.

**Comment by Yamakaja** [comment]
Hey, just to clarify. Are you asking for:

* libiio support on Windows / ARM64, to access remote sensors using the ip / serial / usb backends

or

* Support for the "local" backend, i.e. enabling (lib)iio to access local sensors on your Raspberry PI from Windows?

**Comment by sidd-kishan** [comment]
Dear @Yamakaja ,
                             Please provide us support for:-

`libiio support on Windows / ARM64, to access remote sensors using the ip / serial / usb backends`

so that we can interface analog devices with windows / ARM64 over ip/serial/usb backends and possibly develop instrumentation around libiio on Windows / ARM64

**Comment by Yamakaja** [comment]
I can't really test this myself because i don't have an appropriate device ready, but have you tried building libiio from source on the device? Where does it fail?

**Comment by sidd-kishan** [comment]
I have windows on ARM running on QEMU and have Windows 10 running on Rasberry pi the ARM64 version. I haven't tried building it but if you provide me a build I can test it out on multiple platforms.

**Comment by pcercuei** [comment]
Libiio most likely already works on Windows ARM64. We just don't ship a binary (yet) for it, so you'd have to compile it yourself.

**Comment by rgetz** [comment]
@tfcollins is this (Win/Arm64) something that Azure supports?

**Comment by rgetz** [comment]
Yeah, this was asked for : https://developercommunity.visualstudio.com/t/please-add-a-windows-arm64-hosted-agent/1015752 but it seems to go unanswered...

**Comment by rgetz** [comment]
I will close this, until upstream/prerequisites support this.
