### ISSUE TITLE
Installation of libiio on windows10

### ISSUE THREAD

**Issue by sdrlab** [analogdevicesinc/libiio#712]
Hey,
We've been trying to install libiio on windows 10 (using the installation launcher), and tried running one of the example files (ad9361-iiostream.c) through visual studio ide. But, it returns errors at compilation:

![image](https://user-images.githubusercontent.com/86557358/125190400-9b3cb580-e245-11eb-8bc6-3e340b5d52c0.png)

When we add (char*) at both missing places, it still returns errors:
![image](https://user-images.githubusercontent.com/86557358/125190429-be676500-e245-11eb-95b5-fa0f9e9ce361.png)

Do you have any clue what we are doing wrong? Have others encountered the same problem?

What does the following image mean, does the library not work on windows:
![image](https://user-images.githubusercontent.com/86557358/125190752-5fa2eb00-e247-11eb-9c08-f2102d6be8ca.png)

Our goal is to write a c++ which runs the FPGA and the ad9361 configurations and can accept data and send data with our own arm design.

We've also tried another approach after we encountered a tutorial to run libiio on visual studio here:
https://wiki.analog.com/resources/tools-software/linux-software/building_libiio_for_windows
But we were not able to complete it as the file xmllint.exe was missing in the zip folder.

![image](https://user-images.githubusercontent.com/86557358/125190721-31251000-e247-11eb-9fd9-7404e0bb0abf.png)

Thanks a lot

**Comment by tfcollins** [comment]
Are you linking gains libiio?

**Comment by pcercuei** [comment]
Closing this issue now, since there hasn't been a response for almost 3 months.
