### ISSUE TITLE
Unable to create IIO buffer

### ISSUE THREAD

**Issue by PaperMonoid** [analogdevicesinc/libiio#717]
Hello!

I'm currently trying to connect from MATLAB on Windows to a Linux device using libiio. I'm running the examples presented in the  analog devices wiki, more specifically the [LTE Transmitter and Receiver Example](https://wiki.analog.com/resources/tools-software/linux-software/libiio/clients/lte_example).

The example works on the modes LTE1.4, LTE3 and LTE5 but when I try to run LTE10 the MATLAB program crashes with an error. In the error details it mentions something about `iio_buffer_refill`.

Meanwhile on Linux I get the following error on iiod  `Unable to create buffer` when I run the MATLAB program.

I've used the ARRadio ad9361 with two different FPGAs: SoCKit with Cyclone 5 and also DE10-Standard with Cyclone 5 and I get the same error on both devices when operating on LTE10.

I'm using MATLAB 2017b.

So far I've tried the following:
1. Switching to the MATLAB versions.
2. Switching the libiio versions on both Windows and Linux.
3. Running the adi_update_tools.sh and adi_update_boot.sh that came with the Linux distro (although the adi_update_boot.sh was done manually) as #31 suggests.

What could be causing the error?

Thanks in advance!

**Comment by tfcollins** [comment]
Answering on EZ: https://ez.analog.com/sw-interface-tools/f/q-a/547440/unable-to-create-buffer-on-ad9361-lte10
