### ISSUE TITLE
can't download lib

### ISSUE THREAD

**Issue by ravenkarasu** [analogdevicesinc/libiio#736]
i can't download the libiio lib for windows when i click on the lick i have a message saying 

{"message":"Artifact not found or access denied."}

i just get an ADALM-PULTO SDR and i want to make a custom API but can't download lib

**Comment by tfcollins** [comment]
Please download the installer from the releases page: https://github.com/analogdevicesinc/libiio/releases/download/v0.21/libiio-0.21.g565bf68-Windows-setup.exe
