### ISSUE TITLE
README links to appveyor should be removed

### ISSUE THREAD

**Issue by tfcollins** [analogdevicesinc/libiio#737]
CI switched to Azure and appveyor links are now not functional and should be removed.

**Comment by rgetz** [comment]
Do you have the replacement Azure links?

**Comment by tfcollins** [comment]
https://swdownloads.analog.com/cse/azure_builds/Libiio-Setup-Exe/libiio-setup.exe

**Comment by rgetz** [comment]
I think this is complete - so will close.
