### ISSUE TITLE
fatal: unable to access 'https://github.com/analogdevicesinc/libiio.git/': Empty reply from server

### ISSUE THREAD

**Issue by wangyong5123** [analogdevicesinc/libiio#770]
fatal: unable to access 'https://github.com/analogdevicesinc/libiio.git/': Empty reply from server

why?

**Comment by mhennerich** [comment]
Works for me. Maybe some temporary or regional downtime.

**Comment by pcercuei** [comment]
Either it's a network error, or a temporary error of github, but in any case it is not a problem directly related to the project, so I'll close this bug report now.
