### ISSUE TITLE
iio_attr negative value error for hardwaregain

### ISSUE THREAD

**Issue by ademeren** [analogdevicesinc/libiio#851]
If you try to give negative number for attenuation, software make a mistake and take the "-" symbol as an option. When I was searching, I saw the bug fixed. However, windows version of software still has the same error.

**Comment by rgetz** [comment]
What version of libiio are you using on Windows?

**Comment by rgetz** [comment]
I just tried this on windows 10:

```
C:\Users\rgetz>iio_info -S
Library version: 0.24 (git tag: c4498c2)
...

C:\Users\rgetz>iio_attr -u usb:3.1.5 -c -o ad9361-phy voltage0 hardwaregain
-10.000000 dB

C:\Users\rgetz>iio_attr -u usb:3.1.5 -c -o ad9361-phy voltage0 hardwaregain -6
-6.000000 dB
```

so I think this works, and this issue can be closed.
