### ISSUE TITLE
osx shared library doesn't include the correct (osx) extension

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/libiio#87]
My understanding is that osx shared libraries should have a ".dylib" sufix

Looks like we are building the right file:

adi-mm:build analogdevices$ otool -hv ./iio.framework/iio 
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64  X86_64        ALL  0x00       DYLIB    15       1496   NOUNDEFS DYLDLINK TWOLEVEL NO_REEXPORTED_DYLIBS

(at least it has the same filetype as the other libs):
adi-mm:build analogdevices$ otool -hv /usr/lib/libm.dylib 
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64  X86_64        ALL  0x00       DYLIB    48       3656   NOUNDEFS DYLDLINK TWOLEVEL APP_EXTENSION_SAFE

but it should be "libiio.dylib" or something similar - shouldn't it?

Thanks

**Comment by pcercuei** [comment]
No it shouldn't - please read about OSX frameworks.
