### ISSUE TITLE
iio_attr cannot write attribute

### ISSUE THREAD

**Issue by catkira** [analogdevicesinc/libiio#870]
I am trying to set the rf_port_select attribute of a pluto with iio_attr, but it does not work.

```
# iio_attr -c ad9361-phy voltage0 rf_port_select
B_BALANCED
A
# iio_attr -c ad9361-phy voltage0 rf_port_select A
error Invalid argument (22) while writing 'rf_port_select' with 'A'
A
```
I also tried
```
# iio_attr -c ad9361-phy voltage0 rf_port_select 'A'
error Invalid argument (22) while writing 'rf_port_select' with 'A'
A
```

I am using libiio 0.24, but 1.0 has the same problem.

I also tried to do it without libiio:
```
# cat in_voltage_rf_port_select_available
A_BALANCED B_BALANCED C_BALANCED A_N A_P B_N B_P C_N C_P TX_MONITOR1 TX_MONITOR2 TX_MONITOR1_2
# echo A_BALANCED > in_voltage0_rf_port_select
sh: write error: Invalid argument
#
```

the same method is working when I do it like in [this](https://wiki.analog.com/resources/tools-software/linux-drivers/iio-transceiver/ad9361#:~:text=root%3A/sys/bus/iio/devices/iio%3Adevice1%3E%20cat%20in_voltage0_gain_control_mode%0Aslow_attack%0Aroot%3A/sys/bus/iio/devices/iio%3Adevice1%3E%20echo%20manual%20%3E%20in_voltage0_gain_control_mode%0Aroot%3A/sys/bus/iio/devices/iio%3Adevice1%3E%20cat%20in_voltage0_gain_control_mode%0Amanual) example
```
# echo manual > in_voltage0_gain_control_mode
# cat in_voltage0_gain_control_mode
manual
```

Edit: but I can set manual to `out_voltage0_rf_port_select`
```
# echo A_BALANCED out_voltage0_rf_port_select
A_BALANCED out_voltage0_rf_port_select
```
thats strange, because it should be possible according to `in_voltage_rf_port_select_available`. Also, it should not be possible according to `out_voltage_rf_port_select_available`
```
# cat out_voltage_rf_port_select_available
A B
```
I am confused!

**Comment by tfcollins** [comment]
rf_port_select is not configurable on Pluto as the ports are not physically connected to anything. This port lock is set in devicetree: https://github.com/analogdevicesinc/linux/blob/master/arch/arm/boot/dts/zynq-pluto-sdr.dtsi#L249

-Travis

**Comment by catkira** [comment]
Ok thanks, that makes sense. Pluto only has RX1a, RX2a, TX1a, TX2a as is visible here:
https://wiki.analog.com/_media/university/tools/pluto/hacking/pluto_c.png 

A more comprehensive error message would be nice, or the _available attribute should only show the locked value. Or is it possible the query the lock status of an attribute somehow?
