### ISSUE TITLE
Macro definition of snprintf conflicts on MSVC 14 (VS2015)

### ISSUE THREAD

**Issue by mfumita** [analogdevicesinc/libiio#89]
There is the following code in "iio-private.h".

```C++
#ifdef _MSC_BUILD
#define snprintf sprintf_s  
#define inline __inline  
#endif
```

This cases a build error in Microsoft Visual C++ version 14 which comes from Visual Studio 2015 because "snprintf" is already defined as below.

> Error C1189 #error:  Macro definition of snprintf conflicts with Standard Library function declaration

[https://msdn.microsoft.com/en-us/library/2ts7cx93.aspx](https://msdn.microsoft.com/en-us/library/2ts7cx93.aspx)

I would like to suggest to change the code like below.
```C++
#if _MSC_VER<=1800
#define snprintf sprintf_s
#endif

#ifdef _MSC_BUILD
#define inline __inline
#endif
```

**Comment by pcercuei** [comment]
But then MSVC will complain that we're using snprintf( ) and not the secure version snprintf_s( )...
I think the best way would be to have a iio_snprintf( ) macro that resolves either to snprintf_s if present, or snprintf otherwise.

**Comment by mfumita** [comment]
Thank you for your reply.

I think having a iio_snprintf( ) macro is a proper way as you said. It would be great if you would make this change once you have a chance.
