### ISSUE TITLE
libiio 1.0 does not like certain buffer sizes

### ISSUE THREAD

**Issue by catkira** [analogdevicesinc/libiio#898]
When I chose buffer size 100000 everything is fine:
![image](https://user-images.githubusercontent.com/13425558/188209005-448b6d0f-b73e-4398-ac3f-589f2c4aac92.png)

But when I chose buffer size 1048576 there is sporadic garbage data:
![image](https://user-images.githubusercontent.com/13425558/188208721-5347aed2-4832-460e-a08b-a271264ad55e.png)

Its tested with libiio https://github.com/catkira/libiio/commit/76b2257ef2e2591a907bd0d5f60db6cfb3ee6258running on host and device.

Edit: 500000 is also fine, 800000 already has problems

**Comment by catkira** [comment]
I observed that the pattern of garbage data changes when I change the number of blocks used. When I increase the number of blocks, the garbage data lines are spread further apart.

**Comment by catkira** [comment]
And it also depends on the sample rate. Buffer size 100000 is ok with 10 or 5 MSPS but not ok with 2 or 1 MSPS.

**Comment by catkira** [comment]
never mind, its working now, I was not using direct copy ^^ 
The samples are already interleaved with libiio 1.0.
@pcercuei is this always the case? Or is it possible that the first half of a block is I and the second half of a block Q samples?

**Comment by pcercuei** [comment]
It's always the case, that's how the hardware delivers the samples.

**Comment by catkira** [comment]
ok thanks.
