### ISSUE TITLE
iio_context_get_devices_count

### ISSUE THREAD

**Issue by panxishan** [analogdevicesinc/libiio#914]
There is only one device found by the Libiio computer client through API (iio_context_get_devices_count) through the network connection, there are two devices found through API (iio_context_get_devices_count) through local connection on the ARM board, and there are two IIO devices under the actual connection, why is there one less device found on the computer client?

**Comment by tfcollins** [comment]
Have you loaded/reloaded a driver after boot?

**Comment by tfcollins** [comment]
@panxishan this still an issue?

**Comment by panxishan** [comment]
It has been solved. I must load the driver before starting the iiod
