### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by jpalus** [analogdevicesinc/libiio#920]
`README.md` states that library is licensed under `LGPL v2.1+`, while tests and examples are licensed under `GPL v2+`. Can you clarify what is the license for `iiod`? Also `SPDX-License-Identifier` indicates `LGPL v2.1+` in all source files including tests and examples.

**Comment by pcercuei** [comment]
You are right, the tests and examples .c files' SPDX header is incorrect, it should say GPL v2+. I'll correct that.

About IIOD... I'll have to see, some parts (notably thread-pool.c) could still be LGPL.
