### ISSUE TITLE
Don’t try to build the C# bindings using the Chicken Scheme compiler

### ISSUE THREAD

**Issue by linkmauve** [analogdevicesinc/libiio#95]
Both .NET and Chicken Scheme seem to provide a binary named csc, it would be helpful to test which one it actually is during the cmake step, instead of trying to compile C# code as Scheme.

This broke the ArchLinux package of libiio I maintain, for now I did workaround that by disabling the .NET bindings.

**Comment by rgetz** [comment]
Thanks for reporting. 

Do you have a suggested patch?

**Comment by linkmauve** [comment]
I haven’t had a look yet, I think the ideal thing would be for cmake or extra-cmake-modules to provide a C# module.

I found this example, but it does seem to be quite Windows-specific: https://github.com/SimpleITK/SimpleITK/blob/master/CMake/FindCSharp.cmake

**Comment by pcercuei** [comment]
I think csc is only for compiling the bindings on Windows; Mono's C# compiler is called msc.
So I could just adapt the CMake script to look for the right name on each OS.
