### ISSUE TITLE
 set_blocking_mode warning

### ISSUE THREAD

**Issue by jcn9k** [analogdevicesinc/libiio#96]
This is probably pretty minor.

But I'm getting a warning in the new  set_blocking_mode function for windows.
nonblock is a unsigned int, but ioctlsocket expects an u_long

**Comment by lclausen-adi** [comment]
Thanks for letting us know, this must have slipped in by accident. I remember it was unsigned long at some point. I'll fix it.

**Comment by lclausen-adi** [comment]
Fixed in 04436b2fb85744a46af4bac79d1ecf3be0d08c14

Thanks again.
