### ISSUE TITLE
Device removal causes empty index within |ctx->nb_devices|

### ISSUE THREAD

**Issue by HarveyCHYang** [analogdevicesinc/libiio#974]
Hello,

I'd like to know if the current context supports device removals. It seems that `iio_context.nb_devices` implies devices with id 0~(nb_devices-1) should all exist, while it might not be true if a pluggable device with id != (nb_devices-1) is removed.

Should we support this use case? Thanks!

**Comment by pcercuei** [comment]
Hi @HarveyCHYang,

Libiio does not handle device removals. It would need to be completely redesigned from scratch.

However... I believe that if you remove a device, all Libiio functions that manipulate this IIO device (or channel, or buffer) will return `-ENOENT` (aka. "no such file or directory), because the Linux side cannot access the device's sysfs nodes anymore.
I did not test this, however.

**Comment by HarveyCHYang** [comment]
Thanks Paul!

Do you think it makes sense to return nullptr in `iio_context_get_device` [1] if the device (file/directory) doesn't actually exist, by adding a simple check though?

[1]: https://github.com/analogdevicesinc/libiio/blob/master/context.c#L285

**Comment by pcercuei** [comment]
Unfortunately that would break the ABI :(
Some applications call `iio_context_get_device` in a loop with an incrementing identifier, until it returns NULL. What you suggest would break these applications.

**Comment by HarveyCHYang** [comment]
I forgot to mention: in our use cases (CrOS), we would reload to get a new iio context upon an iio device being unplugged. But I guess that doesn't help, right? As some applications might create a context with empty indices...?

**Comment by HarveyCHYang** [comment]
Ah we have our own logic to support IPC clients with plugged/unplugged devices, so don't really need to disconnect all clients (I assume your talking about other contexts than the local context. In CrOS we only use local context in a service though, and other sensor clients would need to talk to the service with another IPC, called Mojo, to get iio data).

We're just wondering if there's any plan for the unplugged device support in libiio, so that we can save some hacks in our service :)

**Comment by pcercuei** [comment]
Then sorry, it is not planned.

**Comment by HarveyCHYang** [comment]
Thanks for confirming, Paul :)

**Comment by HarveyCHYang** [comment]
Thanks for confirming, Paul :)
