### ISSUE TITLE
iio_buffer_set_blocking_mode returns error

### ISSUE THREAD

**Issue by catkira** [analogdevicesinc/libiio#979]
I am using libiio 0.24 on both sides. When I open a network context to a PlutoSDR and try to make the buffer non-blocking I get this errror: `Failed to set blocking = false, code: -38 error: Function not implemented (38)`
My code looks like this
```
    bool blocking = false;
    int ret = iio_buffer_set_blocking_mode(buffer, blocking);
    if (ret != 0)
    {
        char buf[256];
        iio_strerror(-(int)ret, buf, sizeof(buf));
        std::cerr << "Failed to set blocking = false, code: " << ret << " error: " << buf << std::endl;
    }
```
Does that mean it's not possible to make this buffer non-blocking? How else can I know if there are samples to be picked up without getting a connection timeout? Do I have to use the poll_fd?

**Comment by pcercuei** [comment]
For a change, the error message is actually on-point: the function is simply not implemented in the network, USB or serial backends.

Asking if there are samples to be picked up, means having to send a command to IIOD and wait for the response, which is a blocking call anyway, so there is no way to implement it properly.

Libiio v1.x (of the `pcercuei/dev-new-dmabuf-api` branch) should work much better in that regard.
