### ISSUE TITLE
man pages for applications in ./tests

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/libiio#98]
should we build man pages for iio_info, iio_readdev, and iio_reg?

or just put things in the wiki? (and the man pages point to the wiki?)

-Robin

**Comment by pcercuei** [comment]
It would be great to have man pages, yes.

**Comment by rgetz** [comment]
What should be the master format?

http://asciidoc.org/a2x.1.html
seems to be the way many other cmake projects do it.

(rather than just creating actual troff files).

?

**Comment by pcercuei** [comment]
a2x uses asciidoc, which is itself a 1.0 GiB download size / 1.5 GiB install size on my Debian if I try to apt-get it...
I'm more in favour of not adding dependencies, so I'd prefer actual TROFF files.

**Comment by rgetz** [comment]
OK - closing this, then, expect something tomorrow.
