### ISSUE TITLE
libiio 1.0: cannot create new buffer after cancel operation

### ISSUE THREAD

**Issue by catkira** [analogdevicesinc/libiio#985]
When I abort a dequeue operation with `iio_buffer_cancel` and then try to create a new buffer with `iio_device_create_buffer` I get 
```bash
ERROR: Unable to create buffer: Device or resource busy (16)
```
for about 3 seconds. After that `iio_device_create_buffer` works again without doing anything else. Is this a bug? It would be nice if I could create a new buffer immediately after cancel for my application.
I am using a network context. Latest libiio dev branch is running on host and device.

**Comment by catkira** [comment]
This is the output of iiod when I run it on the device in a terminal
```bash
New client connected from 192.168.137.1
New client connected from 192.168.137.1
New client connected from 192.168.137.1
New client connected from 192.168.137.1
New client connected from 192.168.137.1
New client connected from 192.168.137.1
New client connected from 192.168.137.1
New client connected from 192.168.137.1
New client connected from 192.168.137.1
Client exited
Client exited
Client exited
Client exited
Client exited
Client exited
Client exited
Client exited
Client exited
Client exited
New client connected from 192.168.137.1
Client exited
Client exited
```
for every unsuccessful `iio_device_create_buffer` I get a` New client connected from 192.168.137.1` on the terminal. Then suddenly I get a lot of `Client exited` all at once.

**Comment by catkira** [comment]
Ah I figured out that the `Device or resource busy (16)` errors comes after a cancel operation for the duration of the timeout I set with `iio_context_set_timeout`. So I guess that there is probably an active timeout timer running that is not properly reset when 'iio_buffer_cancel' happens.

**Comment by catkira** [comment]
Even if I don't do `iio_buffer_cancel` and just let the `iio_block_dequeue` timeout, I have to wait another timeout duration before I can create a new buffer.

**Comment by catkira** [comment]
The problem seems to appear only when I run libiio 1.0 on the network client side. local libiio 1.0 and client libiio 0.24 does not show this problem.

**Comment by catkira** [comment]
A call to `iio_buffer_disable()` is also blocking for the duration of a timeout. Inside this call is basically only this code
```c
	err = iio_buffer_set_enabled(buffer, false);
	if (err < 0 && err != -ENOSYS)
		return err;

	iio_task_stop(buffer->worker);
```
`iio_task_stop(buffer->worker);` also appears in `iio_buffer_cancel()` so that's probably the problem.

**Comment by catkira** [comment]
The wait for the condition in iio_task_stop() is probably blocking
```c
void iio_task_stop(struct iio_task *task)
{
	iio_mutex_lock(task->lock);
	task->running = false;
	iio_cond_signal(task->cond);
	iio_cond_wait(task->cond, task->lock, 0);
	iio_mutex_unlock(task->lock);
}
```

**Comment by pcercuei** [comment]
Noted, thanks for testing Libiio v1.0 btw.

**Comment by pcercuei** [comment]
@catkira It should be fixed in the PR https://github.com/analogdevicesinc/libiio/pull/1000

**Comment by pcercuei** [comment]
Closing as this issue was fixed.
